export const A_EMOTION_PROJECTION_ERROR_CODES = Object.freeze({
  CONTEXT_MISMATCH: "A_EMOTION_CONTEXT_MISMATCH",
  AUDIENCE_RESOLUTION_FAILED: "A_EMOTION_AUDIENCE_RESOLUTION_FAILED",
  UNKNOWN_SEAT: "A_EMOTION_UNKNOWN_SEAT",
  DISCLOSURE_BASIS_MISSING: "A_EMOTION_DISCLOSURE_BASIS_MISSING",
  REVEAL_BASE_MISSING: "A_EMOTION_REVEAL_BASE_MISSING",
  PRESENTATION_UNSUPPORTED: "A_EMOTION_PRESENTATION_UNSUPPORTED",
  IDEMPOTENCY_MISMATCH: "A_EMOTION_IDEMPOTENCY_MISMATCH",
  PROJECTION_CONTENT_MISMATCH: "A_EMOTION_PROJECTION_CONTENT_MISMATCH",
  PROJECTION_IDENTITY_MISMATCH: "A_EMOTION_PROJECTION_IDENTITY_MISMATCH",
  PROJECTION_VERSION_UNSUPPORTED: "A_EMOTION_PROJECTION_VERSION_UNSUPPORTED",
  REPOSITORY_CONFLICT: "A_EMOTION_REPOSITORY_CONFLICT",
  CURSOR_INVALID: "A_EMOTION_CURSOR_INVALID",
  DELIVERY_NOT_FOUND: "A_EMOTION_DELIVERY_NOT_FOUND",
  PROJECTION_VERSION_STALE: "A_EMOTION_PROJECTION_VERSION_STALE",
} as const);

export type AEmotionProjectionErrorCode =
  (typeof A_EMOTION_PROJECTION_ERROR_CODES)[keyof typeof A_EMOTION_PROJECTION_ERROR_CODES];

export class AEmotionProjectionError extends Error {
  constructor(
    readonly code: AEmotionProjectionErrorCode,
    readonly detail?: string,
  ) {
    super(`${code}${detail ? `:${detail}` : ""}`);
    this.name = "AEmotionProjectionError";
  }
}

export function failAEmotionProjection(
  code: AEmotionProjectionErrorCode,
  detail?: string,
): never {
  throw new AEmotionProjectionError(code, detail);
}
