export const PRESSURE_PERSISTENCE_ERROR_CODES = Object.freeze({
  FINGERPRINT_MISMATCH: "PRESSURE_PERSISTENCE_FINGERPRINT_MISMATCH",
  WORKING_REVISION_MISMATCH: "PRESSURE_WORKING_REVISION_MISMATCH",
  WORLD_SEQUENCE_MISMATCH: "PRESSURE_WORLD_SEQUENCE_MISMATCH",
  OUTBOX_LEASE_LOST: "PRESSURE_OUTBOX_LEASE_LOST",
  OUTBOX_ATTEMPTS_EXHAUSTED: "PRESSURE_OUTBOX_ATTEMPTS_EXHAUSTED",
  OUTBOX_VOCABULARY_INVALID: "PRESSURE_OUTBOX_VOCABULARY_INVALID",
  INVALID_SEQUENCE_ADVANCE: "PRESSURE_INVALID_SEQUENCE_ADVANCE",
  INVALID_STATUS_TRANSITION: "PRESSURE_INVALID_STATUS_TRANSITION",
  RECORD_NOT_FOUND: "PRESSURE_PERSISTENCE_RECORD_NOT_FOUND",
  RECORD_INVALID: "PRESSURE_PERSISTENCE_RECORD_INVALID",
  AUTHORITY_FENCE_MISMATCH: "PRESSURE_AUTHORITY_FENCE_MISMATCH",
  UNSAFE_DATABASE_SCOPE: "PRESSURE_UNSAFE_DATABASE_SCOPE",
} as const);

export type PressurePersistenceErrorCode =
  (typeof PRESSURE_PERSISTENCE_ERROR_CODES)[keyof typeof PRESSURE_PERSISTENCE_ERROR_CODES];

export class PressurePersistenceError extends Error {
  constructor(
    public readonly code: PressurePersistenceErrorCode,
    message: string,
    public readonly details: Readonly<Record<string, unknown>> = {},
  ) {
    super(message);
    this.name = "PressurePersistenceError";
  }
}
