export const INTERACTION_ERROR_CODES = {
  CONTEXT_MISMATCH: "PRESSURE_INTERACTION_CONTEXT_MISMATCH",
  ROUTE_MISMATCH: "PRESSURE_INTERACTION_ROUTE_MISMATCH",
  INPUT_FINGERPRINT_MISMATCH: "PRESSURE_INTERACTION_INPUT_FINGERPRINT_MISMATCH",
  IDEMPOTENCY_MISMATCH: "PRESSURE_INTERACTION_IDEMPOTENCY_MISMATCH",
  SEAT_NOT_CONTROLLED: "PRESSURE_INTERACTION_SEAT_NOT_CONTROLLED",
  CONTROL_EPOCH_MISMATCH: "PRESSURE_INTERACTION_CONTROL_EPOCH_MISMATCH",
  DECISION_NOT_ACTIVE: "PRESSURE_INTERACTION_DECISION_NOT_ACTIVE",
  ACTION_TYPE_FORBIDDEN: "PRESSURE_INTERACTION_ACTION_TYPE_FORBIDDEN",
  TARGET_FORBIDDEN: "PRESSURE_INTERACTION_TARGET_FORBIDDEN",
  EVIDENCE_FORBIDDEN: "PRESSURE_INTERACTION_EVIDENCE_FORBIDDEN",
  RESOURCE_UNAVAILABLE: "PRESSURE_INTERACTION_RESOURCE_UNAVAILABLE",
  RESERVATION_DUPLICATE: "PRESSURE_INTERACTION_RESERVATION_DUPLICATE",
  INVALID_INTENT: "PRESSURE_INTERACTION_INVALID_INTENT",
  CHAT_INVALID: "PRESSURE_CHAT_INVALID",
  APPEND_CONFLICT: "PRESSURE_INTERACTION_APPEND_CONFLICT",
} as const;

export type InteractionErrorCode =
  (typeof INTERACTION_ERROR_CODES)[keyof typeof INTERACTION_ERROR_CODES];

export class PressureInteractionError extends Error {
  constructor(
    readonly code: InteractionErrorCode,
    readonly detail?: string,
  ) {
    super(detail ? `${code}:${detail}` : code);
    this.name = "PressureInteractionError";
  }
}

export function failInteraction(
  code: InteractionErrorCode,
  detail?: string,
): never {
  throw new PressureInteractionError(code, detail);
}
