import type {
  ActionTargetV1,
  ContactDefinitionV1,
  EvidenceClaimRuleV1,
  InvestigationRouteV1,
  ManeuverActionBindingV1,
  RuleCardDefinitionV1,
  RuleCardHoldingV1,
  WorldTraceV1,
} from "@ai-story/templates";
import type { MvpView } from "../mvp-types";

export const SANGTIAN_MVP_CONTACTS: ContactDefinitionV1[] = [
  {
    actorId: "actor.xunfu",
    roleId: "role.xunfu",
    displayName: "浙江巡抚",
    publicIdentity: "督办改桑新政的地方大员",
    currentAccess: "可以私下召见",
    whyRelevant: "掌握改桑名册、执行官吏和急奏渠道",
    canReceiveEvidence: true,
    visibilityOptions: ["LIMITED", "PUBLIC"],
    accessibleByRoleIds: ["role.zhejiang_governor"],
  },
  {
    actorId: "actor.county_magistrate",
    roleId: "role.county_magistrate",
    displayName: "清流县令",
    publicIdentity: "直接面对民田与粮田压力的地方官",
    currentAccess: "可以通过密信或亲信接触",
    whyRelevant: "掌握县册改痕、田契副本和基层经手记录",
    canReceiveEvidence: true,
    visibilityOptions: ["LIMITED"],
    accessibleByRoleIds: ["role.zhejiang_governor"],
  },
  {
    actorId: "actor.merchant",
    roleId: "role.merchant",
    displayName: "江南商会会首",
    publicIdentity: "控制粮仓、运输与垫银能力的商会代表",
    currentAccess: "可以通过商会帖子约见",
    whyRelevant: "掌握粮路、仓单和官商往来",
    canReceiveEvidence: true,
    visibilityOptions: ["LIMITED", "PUBLIC"],
    accessibleByRoleIds: ["role.zhejiang_governor"],
  },
  {
    actorId: "actor.sili_jian",
    roleId: "role.sili_jian",
    displayName: "司礼监织造使",
    publicIdentity: "代表内廷追问丝源与银路",
    currentAccess: "第三日后可以接触",
    whyRelevant: "拥有直达御前的消息渠道",
    canReceiveEvidence: true,
    visibilityOptions: ["LIMITED", "PUBLIC"],
    accessibleByRoleIds: ["role.zhejiang_governor"],
  },
];

export const SANGTIAN_MVP_TARGETS: ActionTargetV1[] = [
  { type: "LOCATION", id: "location.governor_archive", label: "总督府档房", aliases: ["总督档房"] },
  { type: "LOCATION", id: "location.xunfu_archive", label: "巡抚衙门档房", aliases: ["巡抚档房", "档房"] },
  { type: "LOCATION", id: "location.merchant_warehouse", label: "商会仓房", aliases: ["仓房", "商会仓库"] },
  { type: "DOCUMENT", id: "document.land_register", label: "田契底册", aliases: ["底册", "田契", "名册"] },
  { type: "DOCUMENT", id: "document.memorial", label: "入京奏报", aliases: ["奏报", "奏疏", "密奏"] },
  { type: "INSTITUTION", id: "institution.imperial_court", label: "御前", aliases: ["皇帝", "朝廷"] },
  { type: "RESOURCE", id: "resource.grain_route", label: "粮路", aliases: ["粮道"] },
  { type: "WORLD_ENTITY", id: "entity.sealed_crates", label: "封箱", aliases: ["箱子"] },
];

export const SANGTIAN_MVP_RULE_CARDS: RuleCardDefinitionV1[] = [
  {
    cardKey: "governor_seal_token",
    label: "总督封缄令牌",
    tags: ["AUTHORITY", "SEAL", "LOCATION_CONTROL"],
    allowedRoleKeys: ["zhejiang_governor"],
    timing: ["ACTIVE", "SET", "REACTION"],
    legalTargetTypes: ["LOCATION", "DOCUMENT"],
    capabilityId: "capability.governor.seal_archive",
    triggerPatternIds: ["document_transfer_attempt"],
    guaranteedEffects: ["普通差役会被要求停止继续搬运，并等待权限核验。"],
    duration: { kind: "UNTIL_TURN_END" },
    visibility: {
      beforeTrigger: { scope: "PRIVATE", roleIds: ["role.zhejiang_governor"] },
      afterTrigger: { scope: "PUBLIC" },
    },
    consumption: "COOLDOWN",
    cooldownStages: 2,
    counterTags: ["HIGHER_AUTHORITY", "TRANSFER_ALREADY_COMPLETED", "WRONG_LOCATION"],
    playerFacingLimitations: ["不能追回已经离开目标地点的文件", "不能覆盖更高等级的皇命"],
  },
  {
    cardKey: "county_letter",
    label: "清流县令密信",
    tags: ["RECORD_ACCESS", "PRIVATE_INFORMATION"],
    allowedRoleKeys: ["zhejiang_governor"],
    timing: ["ATTACH", "ACTIVE"],
    legalTargetTypes: ["DOCUMENT", "ACTOR", "INSTITUTION"],
    capabilityId: "capability.governor.use_county_letter",
    triggerPatternIds: [],
    guaranteedEffects: ["可以证明县令曾经提出过具体疑点，并打开相应核验入口。"],
    duration: { kind: "INSTANT" },
    visibility: {
      beforeTrigger: { scope: "PRIVATE", roleIds: ["role.zhejiang_governor"] },
      afterTrigger: { scope: "LIMITED" },
    },
    consumption: "REUSABLE",
    counterTags: ["SOURCE_DISPUTED"],
    playerFacingLimitations: ["密信本身不能证明田契暗账真实存在", "公开后会暴露县令与你的联系"],
  },
  {
    cardKey: "secret_memorial_channel",
    label: "总督密奏渠道",
    tags: ["AUTHORITY", "SECRET_CHANNEL"],
    allowedRoleKeys: ["zhejiang_governor"],
    timing: ["ACTIVE", "REACTION", "ATTACH"],
    legalTargetTypes: ["INSTITUTION", "DOCUMENT"],
    capabilityId: "capability.governor.secret_memorial",
    triggerPatternIds: [],
    guaranteedEffects: ["一份受保护的奏报会进入密奏渠道。"],
    duration: { kind: "INSTANT" },
    visibility: {
      beforeTrigger: { scope: "PRIVATE", roleIds: ["role.zhejiang_governor"] },
      afterTrigger: { scope: "OBSERVABLE" },
    },
    consumption: "COOLDOWN",
    cooldownStages: 2,
    counterTags: ["CHANNEL_DELAYED", "MESSAGE_INTERCEPTED"],
    playerFacingLimitations: ["不能保证御前采信", "密奏可能让内阁或司礼监察觉口径分裂"],
  },
];

export const SANGTIAN_MVP_ACTION_BINDINGS: ManeuverActionBindingV1[] = [
  {
    bindingId: "sangtian.binding.seal_archive",
    effectKey: "seal_archive",
    capabilityId: "capability.governor.seal_archive",
    labels: {
      actionTitle: "封锁档房",
      method: "封锁",
      guaranteedStart: ["封锁命令会送达，兵丁开始前往目标档房。"],
      contestedOutcome: ["兵丁能否在目标物品离开前完成接管", "现场人员是否以权限或人手阻拦"],
      notGuaranteed: ["底册仍然留在档房", "已经离开的文件会被追回"],
      confirmLabel: "确认封锁档房",
    },
    legalTargetTypes: ["LOCATION"],
    defaultVisibility: { scope: "PUBLIC" },
    tracePolicy: { leavesTrace: true, playerSafeHint: "相关官员会看到兵丁和封锁命令到达。" },
    reactionPolicy: { mode: "ALWAYS", playerSafeHint: "控制该地点或拥有更高权限的人可能获得应变机会。" },
    timing: { startsAt: "ON_COMMIT", settlesAt: { kind: "CURRENT_SETTLEMENT" }, playerLabel: "本场景结算时" },
    costs: [{ kind: "RESOURCE", id: "guards", amount: 1, label: "兵丁 1 队" }],
  },
  {
    bindingId: "sangtian.binding.move_document",
    effectKey: "move_document",
    capabilityId: "capability.governor.move_document",
    labels: {
      actionTitle: "转移底册",
      method: "转移",
      guaranteedStart: ["经手人会收到转移命令，并开始接触目标文件。"],
      contestedOutcome: ["文件能否在被发现或封锁前离开原处"],
      notGuaranteed: ["转移不会留下经手、路线或登记痕迹", "目标文件一定完整真实"],
      confirmLabel: "确认转移底册",
    },
    legalTargetTypes: ["DOCUMENT", "WORLD_ENTITY"],
    defaultVisibility: { scope: "OBSERVABLE" },
    tracePolicy: { leavesTrace: true, playerSafeHint: "搬运可能留下经手人、封箱、登记和路线痕迹。" },
    reactionPolicy: { mode: "IF_OBSERVED", playerSafeHint: "察觉搬运的人可能应变。" },
    timing: { startsAt: "ON_COMMIT", settlesAt: { kind: "CURRENT_SETTLEMENT" }, playerLabel: "本场景结算时" },
    costs: [],
  },
  {
    bindingId: "sangtian.binding.protect_person",
    effectKey: "protect_person",
    capabilityId: "capability.governor.protect_person",
    labels: {
      actionTitle: "保护经手人",
      method: "保护",
      guaranteedStart: ["保护命令会送达，可信人手开始接触目标。"],
      contestedOutcome: ["保护能否在对手施压、调职或拘押之前建立"],
      notGuaranteed: ["目标会因此完全信任你", "目标掌握的证词一定真实"],
      confirmLabel: "确认保护经手人",
    },
    legalTargetTypes: ["ACTOR", "PERSON", "ROLE"],
    defaultVisibility: { scope: "OBSERVABLE" },
    tracePolicy: { leavesTrace: true, playerSafeHint: "目标及其周围的人可能察觉保护安排。" },
    reactionPolicy: { mode: "IF_OBSERVED", playerSafeHint: "原本控制目标的人可能改变做法。" },
    timing: { startsAt: "ON_COMMIT", settlesAt: { kind: "CURRENT_SETTLEMENT" }, playerLabel: "本场景结算时" },
    costs: [{ kind: "RESOURCE", id: "staff", amount: 1, label: "幕僚 1 人" }],
  },
  {
    bindingId: "sangtian.binding.submit_memorial",
    effectKey: "submit_memorial",
    capabilityId: "capability.governor.submit_memorial",
    labels: {
      actionTitle: "提交奏报",
      method: "上奏",
      guaranteedStart: ["奏报会完成封缄并离开总督府。"],
      contestedOutcome: ["奏报何时抵达、由谁先看到以及是否被采信"],
      notGuaranteed: ["御前会按你的解释裁定", "其他奏报不会先到"],
      confirmLabel: "确认送出奏报",
    },
    legalTargetTypes: ["DOCUMENT", "INSTITUTION"],
    defaultVisibility: { scope: "OBSERVABLE" },
    tracePolicy: { leavesTrace: true, playerSafeHint: "驿站、封缄和经手记录可能让其他势力察觉奏报已出。" },
    reactionPolicy: { mode: "IF_OBSERVED", playerSafeHint: "争夺奏报口径的人可能采取行动。" },
    timing: { startsAt: "ON_COMMIT", settlesAt: { kind: "CURRENT_SETTLEMENT" }, playerLabel: "奏报离府后进入后续结算" },
    costs: [],
  },
];

export const SANGTIAN_MVP_EVIDENCE_CLAIMS: EvidenceClaimRuleV1[] = [
  {
    claimKey: "claim.register_amended",
    label: "现有底册曾被重新装订或修改",
    requiredIndependentSourceGroups: 2,
    minimumTotalStrength: 4,
    resultingLevel: "PROOF",
    resultingStatement: "两份独立痕迹能够确认现有底册曾被重新装订或修改。",
    forbiddenSameSourceStacking: true,
  },
];

export function initialSangtianMvpTraces(runId: string): WorldTraceV1[] {
  return [
    {
      traceId: "trace.register.amended_pages",
      runId,
      title: "名册上颜色略新的三页纸",
      narrativeHook: "三页纸张颜色与前后不同，装订孔也有轻微错位。",
      traceType: "PHYSICAL",
      subjectEntityIds: ["document.land_register"],
      sourceEventIds: ["event.run_created"],
      supportedClaimKeys: ["claim.register_amended"],
      sourceGroupKey: "source.register.physical",
      accessRoleIds: ["role.zhejiang_governor"],
      routeIds: ["route.compare_paper_and_seal", "route.check_copy_registry"],
      visibility: { scope: "PRIVATE", roleIds: ["role.zhejiang_governor"] },
      status: "ACTIVE",
      createdAtRevision: 1,
      expiresAtStage: 3,
    },
    {
      traceId: "trace.xunfu.messenger",
      runId,
      title: "巡抚幕僚频繁出入驿站",
      narrativeHook: "同一名幕僚两日内三次进入驿站，却没有对应的公开公文。",
      traceType: "BEHAVIOR",
      subjectEntityIds: ["actor.xunfu"],
      sourceEventIds: ["event.run_created"],
      supportedClaimKeys: ["claim.xunfu_private_dispatch"],
      sourceGroupKey: "source.xunfu.messenger",
      accessRoleIds: ["role.zhejiang_governor"],
      routeIds: ["route.read_inn_registry", "route.follow_messenger"],
      visibility: { scope: "PRIVATE", roleIds: ["role.zhejiang_governor"] },
      status: "ACTIVE",
      createdAtRevision: 1,
      expiresAtStage: 2,
    },
  ];
}

export const SANGTIAN_MVP_INVESTIGATION_ROUTES: InvestigationRouteV1[] = [
  {
    routeId: "route.compare_paper_and_seal",
    traceId: "trace.register.amended_pages",
    label: "核对纸张、印章与装订孔",
    narrativeMethod: "让幕僚在内厅逐页核对纸张年代、印章压痕和装订孔位置",
    requiredCapabilityIds: ["capability.governor.inspect_records"],
    requiredResourceCosts: [{ resourceId: "staff", amount: 1, label: "幕僚" }],
    optionalCardTags: ["RECORD_ACCESS"],
    revealRules: [{
      claimKey: "claim.register_amended",
      statement: "三页底册的纸张、压印与装订孔和前后页不一致。",
      strength: 2,
      when: "ALWAYS",
    }],
    evidenceCeiling: "CORROBORATION",
    mayLearn: ["哪些页曾被重新装订", "纸张与印章是否和原册一致"],
    cannotProve: ["是谁替换了这些页", "被替换的内容现在在哪里"],
    settlementMoment: { kind: "IMMEDIATE_AFTER_COMMIT" },
    observableTrail: null,
    counterTags: ["RECORD_FORGED"],
    expiresWithTrace: true,
  },
  {
    routeId: "route.check_copy_registry",
    traceId: "trace.register.amended_pages",
    label: "调取县衙副册交叉核验",
    narrativeMethod: "通过县令渠道调取同一编号的副册，把三页内容和地方留档逐项对照",
    requiredCapabilityIds: ["capability.governor.inspect_records"],
    requiredResourceCosts: [{ resourceId: "staff", amount: 1, label: "幕僚" }],
    optionalCardTags: ["RECORD_ACCESS"],
    revealRules: [{
      claimKey: "claim.register_amended",
      statement: "县衙副册与总册在三处田亩编号上存在不一致。",
      strength: 2,
      when: "ALWAYS",
    }],
    evidenceCeiling: "CORROBORATION",
    mayLearn: ["总册与副册的具体差异", "差异涉及哪些田亩编号"],
    cannotProve: ["差异由谁故意造成", "巡抚本人是否知情"],
    settlementMoment: { kind: "IMMEDIATE_AFTER_COMMIT" },
    observableTrail: {
      summary: "县衙会知道总督府正在调取副册。",
      audiencePolicyId: "county-record-office",
    },
    counterTags: ["COPY_MISSING", "ACCESS_BLOCKED"],
    expiresWithTrace: true,
  },
  {
    routeId: "route.read_inn_registry",
    traceId: "trace.xunfu.messenger",
    label: "查阅驿站登记",
    narrativeMethod: "让幕僚核对驿站登记、出发时辰和经手人员",
    requiredCapabilityIds: ["capability.governor.inspect_records"],
    requiredResourceCosts: [{ resourceId: "staff", amount: 1, label: "幕僚" }],
    optionalCardTags: [],
    revealRules: [{
      claimKey: "claim.xunfu_private_dispatch",
      statement: "巡抚幕僚在没有公开公文的情况下办理过一次加急递送。",
      strength: 2,
      when: "ALWAYS",
    }],
    evidenceCeiling: "CORROBORATION",
    mayLearn: ["急递离开的时辰", "登记经手人和递送等级"],
    cannotProve: ["信中具体内容", "巡抚本人是否亲自下令"],
    settlementMoment: { kind: "IMMEDIATE_AFTER_COMMIT" },
    observableTrail: {
      summary: "驿站经手人可能把查阅记录的消息传回巡抚府。",
      audiencePolicyId: "xunfu-messenger-network",
    },
    counterTags: ["RECORD_FORGED", "ACCESS_BLOCKED"],
    expiresWithTrace: true,
  },
  {
    routeId: "route.follow_messenger",
    traceId: "trace.xunfu.messenger",
    label: "暗中跟随驿站幕僚",
    narrativeMethod: "让熟悉城门的亲信不接触文书，只沿路线确认幕僚最终去向",
    requiredCapabilityIds: ["capability.governor.dispatch_agent"],
    requiredResourceCosts: [{ resourceId: "staff", amount: 1, label: "幕僚" }],
    optionalCardTags: [],
    revealRules: [{
      claimKey: "claim.xunfu_messenger_route",
      statement: "巡抚幕僚在离开驿站后转往一处非公开会面地点。",
      strength: 1,
      when: "ALWAYS",
    }],
    evidenceCeiling: "LEAD",
    mayLearn: ["幕僚离开驿站后的路线", "可能接触的人或地点"],
    cannotProve: ["递送文书的内容", "会面双方达成了什么"],
    settlementMoment: { kind: "NEXT_ACTOR_TURN" },
    observableTrail: {
      summary: "被跟随的幕僚可能察觉身后有人。",
      audiencePolicyId: "tracked-messenger",
    },
    counterTags: ["TAIL_DETECTED", "ROUTE_CHANGED"],
    expiresWithTrace: true,
  },
];

export function initialSangtianMvpRuleCardHoldings(): RuleCardHoldingV1[] {
  return [
    { cardAssetKey: "asset.governor_seal_token", cardKey: "governor_seal_token", ownerRoleId: "role.zhejiang_governor", status: "AVAILABLE" },
    { cardAssetKey: "asset.county_letter", cardKey: "county_letter", ownerRoleId: "role.zhejiang_governor", status: "AVAILABLE" },
    { cardAssetKey: "asset.secret_memorial_channel", cardKey: "secret_memorial_channel", ownerRoleId: "role.zhejiang_governor", status: "AVAILABLE" },
  ];
}

export function contactsForMvpView(view: MvpView): ContactDefinitionV1[] {
  return SANGTIAN_MVP_CONTACTS.filter((contact) => contact.actorId !== "actor.sili_jian" || view.run.currentDay >= 3);
}
