import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Our Many Worlds 首页包含真实资源、World API 目录和统一三步说明", async () => {
  const [html, script, css, worldApi] = await Promise.all([
    readFile(new URL("../public/home.html", import.meta.url), "utf8"),
    readFile(new URL("../public/home.js", import.meta.url), "utf8"),
    readFile(new URL("../public/home.css", import.meta.url), "utf8"),
    readFile(new URL("../public/world-api.js", import.meta.url), "utf8")
  ]);

  assert.match(html, /home\.js\?v=/);
  assert.match(html, /Our Many Worlds/);
  assert.match(html, /Our Many Worlds \| Real players\. Living worlds\./);
  assert.match(script, /Our Many Worlds<small>Real players\. Living worlds\.<\/small>/);
  assert.match(html, /rel="icon"[^>]+many-worlds-logo\.png/);
  assert.match(html, /rel="apple-touch-icon"[^>]+many-worlds-logo\.png/);
  assert.doesNotMatch(html, /AI 故事局/);
  assert.match(script, /\/assets\/brand\/many-worlds-logo\.png/);
  assert.match(script, /Everyone sees a <em>different truth<\/em>\.<br\/>Everyone changes the <em>same world<\/em>\./);
  assert.match(script, /AI-POWERED SHARED WORLDS/);
  assert.match(script, /Enter a living world as a character with your own goals, secrets, relationships, and limited point of view\./);
  assert.match(script, /AI resolves everyone's moves into one shared world—and every choice can change what others know, believe, and do\./);
  assert.match(script, /href="#how-it-works">\$\{icon\(4\)\} See How It Plays<\/a>/);
  assert.match(script, /Different goals and secrets/);
  assert.match(script, /Your choices affect other players/);
  assert.match(script, /fetchWorldCatalog/);
  assert.match(worldApi, /\/api\/v4\/worlds/);
  assert.doesNotMatch(script, /from "\.\/world-catalog\.js"/);
  assert.match(script, /Worlds worth stepping into/);
  assert.match(script, /Not a story with branches/);
  assert.match(script, /How It Plays/);
  assert.match(script, /One shared world shaped by everyone/);
  assert.match(script, /Choose a role\. Make your move\. Watch private goals and decisions collide in one shared world\./);
  assert.match(script, /Choose a World and Role/);
  assert.match(script, /Enter as a character with your own goal, private information, relationships, and leverage\./);
  assert.match(script, /Make Your Move/);
  assert.match(script, /Talk, investigate, bargain, use leverage, or describe your own action in your own words\./);
  assert.match(script, /Face the Consequences/);
  assert.match(script, /See how your move changes your position, other players' choices, and the shared world\./);
  assert.equal((script.match(/id="how-it-works"/g) || []).length, 1);
  assert.match(script, /class="how-it-works-showcase" id="how-it-works"/);
  assert.doesNotMatch(script, /class="principles"|class="entry-grid"|class="flow-section|class="ending-section/);
  assert.doesNotMatch(script, /How a world unfolds|When the run ends, see what really happened/);
  assert.doesNotMatch(script, /Open a room, not a script|Room Overview|Room Tensions/);
  assert.doesNotMatch(script, /\/#create/);
  assert.match(script, /href="\/rooms\?worldId=caesar">Create<\/a>/);
  assert.match(script, /World Credits/);
  assert.match(script, /New account reward/);
  assert.match(script, /\+50 World Credits/);
  assert.match(script, /300[\s\S]*World Credits[\s\S]*\$7\.99/);
  assert.match(script, /650[\s\S]*World Credits[\s\S]*\$14\.99/);
  assert.match(script, /Best value/);
  assert.match(script, /Referral reward/);
  assert.match(script, /\+25 World Credits/);
  assert.match(script, /eligible referral/);
  assert.match(script, /The exact Credit cost is shown before you confirm any use/);
  assert.match(script, /href="\/credits"/);
  assert.match(script, /href="\/credits\?confirm=credits_300"/);
  assert.match(script, /href="\/credits\?confirm=credits_650"/);
  assert.doesNotMatch(script, /credits\.html|#flow|#explore/);
  assert.doesNotMatch(script, /Many Worlds Plus/);
  assert.doesNotMatch(script, /\/ month/);
  assert.match(script, /class="faq-section faq-simple mw-panel"/);
  assert.match(script, /Frequently Asked Questions/);
  assert.match(script, /Clear answers about shared worlds, private roles, Solo and Multiplayer play, AI resolution, and World Credits\./);
  const faqItemsSource = script.match(/const faqItems = \[([\s\S]*?)\n\];/)?.[1] || "";
  assert.equal((faqItemsSource.match(/^\s*\["/gm) || []).length, 10);
  assert.match(faqItemsSource, /How is this different from a normal interactive story\?/);
  assert.match(faqItemsSource, /What can I do during a run\?/);
  assert.match(faqItemsSource, /Do all players see the same information\?/);
  assert.match(faqItemsSource, /Can I create a room and invite real people\?/);
  assert.match(faqItemsSource, /AI acts as the world simulator, the performer for unfilled roles, and the narrator of consequences\./);
  assert.match(faqItemsSource, /Creating a run costs 20 Credits\. A suggested action costs 1 Credit, and a custom or complex action costs 2 Credits\./);
  assert.match(faqItemsSource, /The current purchase and referral terms are always shown before you confirm\./);
  assert.doesNotMatch(script, /faq-layout|faq-intro|faq-notes|faq-content|faq-cta/);
  assert.match(css, /\.faq-section\.faq-simple\s*\{[\s\S]*?width:\s*min\(1320px, calc\(100vw - 48px\)\)/);
  assert.match(css, /\.faq-simple-head h2\s*\{[\s\S]*?font-size:\s*48px/);
  assert.match(css, /\.faq-simple \.faq-grid details\s*\{[\s\S]*?font-size:\s*19px/);
  assert.match(css, /\.faq-simple \.faq-grid details p\s*\{[\s\S]*?font-size:\s*17px/);
  assert.ok(script.indexOf('id="pricing"') < script.indexOf('id="faq"'));
  assert.match(script, /What are World Credits/);
  assert.match(script, /How can I get World Credits/);
  assert.doesNotMatch(script, /How do World Credits unlock a room/);
  assert.doesNotMatch(script, /The first three decisions are free/i);
  assert.doesNotMatch(script, /100\s+Credits\s*\/\s*room/i);
  assert.doesNotMatch(script, /per-turn/i);
  assert.doesNotMatch(script, /Creating a room is free/i);
  assert.doesNotMatch(script, /Purchased Credits never expire/i);
  assert.doesNotMatch(script, /Bonus Credits expire/i);
  assert.doesNotMatch(script, /two reward slots/i);
  assert.match(script, /browserWindow\.location\.href = "\/worlds"/);
  assert.match(script, /many_worlds_session_hint=1/);
  assert.match(script, /fetch\("\/api\/v4\/auth\/me"/);
  assert.match(script, /credentials: "include"/);
  assert.doesNotMatch(script, /<img src="\/assets\/icon\/17\.png"/);
  assert.match(script, /account\?\.email \|\| account\?\.nickname \|\| "M"/);
  assert.match(script, /esc\(accountInitial\(account\)\)/);
  assert.match(script, /My Account/);
  assert.match(script, /href="\/account"/);
  assert.match(script, /Logout/);
  assert.match(script, /\/api\/v4\/auth\/logout/);
  assert.match(script, /disableAutoSelect/);
  assert.doesNotMatch(script, /account-name|>My rooms</);
  assert.match(script, /function asset\(group, index\)/);
  assert.match(script, /worlds\.slice\(0, 6\)/);
  assert.match(script, /setInterval/);
  assert.match(script, /CAROUSEL_TRANSITION_MS = 650/);
  assert.match(script, /CAROUSEL_AUTOPLAY_MS = 3000/);
  assert.match(script, /carouselRole/);
  assert.match(script, /showCarouselItem/);
  assert.match(script, /data-carousel-item/);
  assert.doesNotMatch(script, /data-carousel-prev|data-carousel-next|carousel-controls/);
  assert.match(script, /renderHeroCarousel/);
  assert.match(script, /hero-card/);
  assert.match(script, /world\.imageUrl/);
  assert.match(script, /asset\("portrait"/);
  assert.match(script, /asset\("icon"/);
  assert.match(css, /\.mw-hero/);
  assert.match(css, /\.many-worlds-page \.how-it-works-showcase/);
  assert.match(css, /\.how-steps\s*\{[\s\S]*?grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.how-step-icon\s*\{[\s\S]*?width:\s*178px/);
  assert.match(css, /Stacked hero composition/);
  assert.match(css, /\.many-worlds-page \.mw-hero \{[\s\S]*?flex-direction: column/);
  assert.match(css, /\.mw-header nav \{ position: absolute; left: 50%/);
  assert.match(css, /\.account-trigger/);
  assert.match(css, /width: 36px; height: 36px/);
  assert.match(css, /\.account-menu/);
  assert.match(css, /\.world-carousel/);
  assert.match(css, /\.carousel-item\[data-role="center"\]/);
  assert.match(css, /650ms cubic-bezier\(\.4,0,\.2,1\)/);
  assert.doesNotMatch(css, /\.carousel-controls/);
  assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media/);
});
