export const SEAT_CONTROL_ERROR_CODES = Object.freeze({
  INVALID_COMMAND: "SEAT_CONTROL_INVALID_COMMAND",
  GENESIS_NOT_COMMITTED: "SEAT_CONTROL_GENESIS_NOT_COMMITTED",
  GENESIS_MISMATCH: "SEAT_CONTROL_GENESIS_MISMATCH",
  FROZEN_POLICY_MISSING: "SEAT_CONTROL_FROZEN_POLICY_MISSING",
  FROZEN_POLICY_MISMATCH: "SEAT_CONTROL_FROZEN_POLICY_MISMATCH",
  RUN_NOT_INITIALIZED: "SEAT_CONTROL_RUN_NOT_INITIALIZED",
  RUN_ALREADY_INITIALIZED: "SEAT_CONTROL_RUN_ALREADY_INITIALIZED",
  CONTROL_CHANGED: "SEAT_CONTROL_CHANGED",
  STALE_CONTROL_EPOCH: "SEAT_CONTROL_STALE_CONTROL_EPOCH",
  FENCE_REJECTED: "SEAT_CONTROL_FENCE_REJECTED",
  CONTROLLER_FORBIDDEN: "SEAT_CONTROL_CONTROLLER_FORBIDDEN",
  TRANSITION_NOT_ALLOWED: "SEAT_CONTROL_TRANSITION_NOT_ALLOWED",
  IDEMPOTENCY_KEY_REUSED: "SEAT_CONTROL_IDEMPOTENCY_KEY_REUSED",
  ATOMIC_COMMIT_CONFLICT: "SEAT_CONTROL_ATOMIC_COMMIT_CONFLICT",
  PORT_RESULT_INVALID: "SEAT_CONTROL_PORT_RESULT_INVALID",
  PRIVATE_PROJECTION_INVALID: "SEAT_CONTROL_PRIVATE_PROJECTION_INVALID",
} as const);

export type SeatControlErrorCodeV1 =
  (typeof SEAT_CONTROL_ERROR_CODES)[keyof typeof SEAT_CONTROL_ERROR_CODES];

export class SeatControlError extends Error {
  readonly code: SeatControlErrorCodeV1;
  readonly detail: string | null;

  constructor(code: SeatControlErrorCodeV1, detail?: string) {
    super(detail ? `${code}:${detail}` : code);
    this.name = "SeatControlError";
    this.code = code;
    this.detail = detail ?? null;
  }
}

export function failSeatControl(
  code: SeatControlErrorCodeV1,
  detail?: string,
): never {
  throw new SeatControlError(code, detail);
}
