export type B0ChapterSettlementErrorCodeV1 =
  | "WIRE_INPUT_INVALID"
  | "INPUT_SCHEMA_INVALID"
  | "B0_INPUT_HASH_MISMATCH"
  | "RUN_CHAPTER_FINGERPRINT_MISMATCH"
  | "BASE_WORLD_SEQUENCE_MISMATCH"
  | "SIX_SEAT_TOPOLOGY_INVALID"
  | "ACTION_SET_MISMATCH"
  | "ACTION_CONTEXT_MISMATCH"
  | "RESOURCE_SNAPSHOT_INVALID"
  | "RESOURCE_COMMITMENT_DUPLICATE"
  | "RESOURCE_VERSION_MISMATCH"
  | "RESOURCE_INSUFFICIENT"
  | "EVALUATION_SCHEMA_INVALID"
  | "EVALUATION_CONTEXT_MISMATCH"
  | "EVALUATION_HASH_MISMATCH"
  | "RESOURCE_DISPOSITION_MISMATCH"
  | "WORLD_MUTATION_CONFLICT"
  | "CAUSAL_REFERENCE_INVALID"
  | "REQUEST_FINGERPRINT_MISMATCH"
  | "IDEMPOTENCY_KEY_MISMATCH"
  | "CHAPTER_SETTLEMENT_FINGERPRINT_MISMATCH"
  | "STORED_RECEIPT_INVALID";

export class B0ChapterSettlementErrorV1 extends Error {
  constructor(
    public readonly code: B0ChapterSettlementErrorCodeV1,
    message: string,
  ) {
    super(message);
    this.name = "B0ChapterSettlementErrorV1";
  }
}
