import { durableEntityKinds, type CausalCondition, type CausalEvent, type DurablePredicate, type DurableTurnEnvelope, type VisibilityRule, type WorldRuntimeContract } from "./types";

const ID = /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/;
const VERSION = /^\d+\.\d+\.\d+$/;
const PREDICATE_FIELDS: Record<string, readonly string[]> = {
  "ENTITY.INTRODUCED": ["type", "entityId"], "ENTITY.LOCATED_AT": ["type", "entityId", "locationId"], "ENTITY.HELD_BY": ["type", "entityId", "actorId"],
  "DOCUMENT.CREATED": ["type", "documentId"], "DOCUMENT.AUTHENTICATED": ["type", "documentId", "actorId"], "DOCUMENT.TRANSFERRED": ["type", "documentId", "fromActorId", "toActorId"], "DOCUMENT.PUBLISHED": ["type", "documentId", "audienceId"],
  "EVIDENCE.DESTROYED": ["type", "evidenceId"], "KNOWLEDGE.REVEALED_TO": ["type", "secretId", "actorId"], "ACTOR.COMMITTED": ["type", "actorId", "commitmentId"], "ACTOR.ORDERED": ["type", "actorId", "capabilityId"],
  "RELATION.TRUST_CHANGED": ["type", "fromActorId", "toActorId", "delta"], "RELATION.SUSPICION_CHANGED": ["type", "fromActorId", "toActorId", "delta"], "WORLD.PRESSURE_CHANGED": ["type", "pressureId", "delta"], "RESOURCE.CHANGED": ["type", "actorId", "resourceId", "delta"]
};
const CONTRACT_FIELDS = ["worldId", "contractVersion", "aliases", "title", "entities", "roles", "actorPolicies", "capabilities", "knowledgeAcl", "destinyHooks", "causalRules", "delayedRules", "styleProfile", "openingState", "openingProjections"];

function fail(code: string, detail: string): never { throw new Error(`${code}:${detail}`); }
function object(value: unknown, code: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) fail(code, "OBJECT_REQUIRED"); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, fields: readonly string[], code: string) { for (const key of Object.keys(value)) if (!fields.includes(key)) fail("RUNTIME_CONTRACT_UNKNOWN_FIELD", `${code}.${key}`); for (const key of fields) if (!(key in value)) fail(code, `MISSING_${key}`); }
function id(value: unknown, label: string): string { if (typeof value !== "string" || !ID.test(value)) fail("RUNTIME_CONTRACT_ID_INVALID", label); return value; }
function strings(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some(v => typeof v !== "string")) fail("RUNTIME_CONTRACT_ARRAY_INVALID", label); return value as string[]; }
function unique(items: string[], label: string) { const seen = new Set<string>(); for (const item of items) { if (seen.has(item)) fail("RUNTIME_CONTRACT_DUPLICATE_ID", `${label}.${item}`); seen.add(item); } }

function validateVisibility(input: unknown, actorIds: Set<string>, policyIds: Set<string>, eventIds = new Set<string>()): VisibilityRule {
  const value = object(input, "VISIBILITY_INVALID");
  if (value.scope === "PUBLIC") exact(value, ["scope"], "VISIBILITY_INVALID");
  else if (value.scope === "PRIVATE") { exact(value, ["scope", "actorId"], "VISIBILITY_INVALID"); if (!actorIds.has(String(value.actorId))) fail("RUNTIME_CONTRACT_DANGLING_ACTOR", String(value.actorId)); }
  else if (value.scope === "ACTOR_SET") { exact(value, ["scope", "actorIds"], "VISIBILITY_INVALID"); const ids = strings(value.actorIds, "visibility.actorIds"); if (!ids.length) fail("VISIBILITY_INVALID", "EMPTY_ACTOR_SET"); unique(ids, "visibility.actorIds"); ids.forEach(v => { if (!actorIds.has(v)) fail("RUNTIME_CONTRACT_DANGLING_ACTOR", v); }); }
  else if (value.scope === "RELATION_BASED") { exact(value, ["scope", "policyId"], "VISIBILITY_INVALID"); if (!policyIds.has(String(value.policyId))) fail("RUNTIME_CONTRACT_DANGLING_POLICY", String(value.policyId)); }
  else if (value.scope === "INFERABLE") { exact(value, ["scope", "evidenceEventIds"], "VISIBILITY_INVALID"); strings(value.evidenceEventIds, "visibility.evidenceEventIds").forEach(v => { if (!eventIds.has(v)) fail("RUNTIME_CONTRACT_DANGLING_EVENT", v); }); }
  else fail("VISIBILITY_INVALID", String(value.scope));
  return value as VisibilityRule;
}

export function validateDurablePredicate(input: unknown, entities: Map<string, string>, capabilities: Set<string>): DurablePredicate {
  const value = object(input, "PREDICATE_INVALID"); const fields = PREDICATE_FIELDS[String(value.type)];
  if (!fields) fail("PREDICATE_KIND_INVALID", String(value.type)); exact(value, fields, "PREDICATE_INVALID");
  for (const [key, raw] of Object.entries(value)) {
    if (key === "type") continue;
    if (key === "delta") { if (typeof raw !== "number" || !Number.isFinite(raw) || raw === 0) fail("PREDICATE_INVALID", "delta"); continue; }
    const ref = id(raw, key);
    const expected = key.includes("actor") || key === "fromActorId" || key === "toActorId" ? "ACTOR" : key === "locationId" ? "LOCATION" : key === "documentId" ? "DOCUMENT" : key === "evidenceId" ? "EVIDENCE" : key === "secretId" ? "SECRET" : key === "resourceId" ? "RESOURCE" : undefined;
    if (key === "capabilityId") { if (!capabilities.has(ref)) fail("RUNTIME_CONTRACT_DANGLING_CAPABILITY", ref); }
    else if (expected && entities.get(ref) !== expected) fail("RUNTIME_CONTRACT_REFERENCE_KIND", `${key}.${ref}.${expected}`);
    else if (key === "entityId" && !entities.has(ref)) fail("RUNTIME_CONTRACT_DANGLING_ENTITY", ref);
  }
  return value as DurablePredicate;
}

function predicatesFromCondition(condition: CausalCondition): DurablePredicate[] { return "all" in condition ? condition.all : "any" in condition ? condition.any : [condition.not]; }
function validateCondition(input: unknown, entities: Map<string, string>, capabilities: Set<string>): CausalCondition {
  const value = object(input, "CONDITION_INVALID"); exact(value, Object.keys(value), "CONDITION_INVALID");
  const keys = ["all", "any", "not"].filter(k => k in value); if (keys.length !== 1) fail("CONDITION_INVALID", "EXACTLY_ONE_OPERATOR");
  if (keys[0] === "not") return { not: validateDurablePredicate(value.not, entities, capabilities) };
  const list = value[keys[0]]; if (!Array.isArray(list) || !list.length) fail("CONDITION_INVALID", "EMPTY");
  return { [keys[0]]: list.map(v => validateDurablePredicate(v, entities, capabilities)) } as CausalCondition;
}

export function validateWorldRuntimeContract(input: unknown): WorldRuntimeContract {
  const value = object(input, "RUNTIME_CONTRACT_INVALID"); exact(value, CONTRACT_FIELDS, "RUNTIME_CONTRACT_INVALID");
  const worldId = id(value.worldId, "worldId"); if (typeof value.contractVersion !== "string" || !VERSION.test(value.contractVersion)) fail("RUNTIME_CONTRACT_VERSION_INVALID", String(value.contractVersion));
  strings(value.aliases, "aliases"); if (typeof value.title !== "string" || !value.title) fail("RUNTIME_CONTRACT_INVALID", "title");
  if (!Array.isArray(value.entities)) fail("RUNTIME_CONTRACT_INVALID", "entities");
  const entities = new Map<string, string>();
  for (const raw of value.entities) { const e = object(raw, "ENTITY_INVALID"); const fields = ["id", "kind", "displayName", "aliases", "durable", ...(e.visibilityPolicyId === undefined ? [] : ["visibilityPolicyId"]), "initialStatus"]; exact(e, fields, "ENTITY_INVALID"); const eid = id(e.id, "entity.id"); if (entities.has(eid)) fail("RUNTIME_CONTRACT_DUPLICATE_ID", eid); if (!durableEntityKinds.includes(e.kind as never)) fail("ENTITY_KIND_INVALID", String(e.kind)); if (e.durable !== true) fail("ENTITY_INVALID", "durable"); if (typeof e.displayName !== "string") fail("ENTITY_INVALID", "displayName"); strings(e.aliases, "entity.aliases"); object(e.initialStatus, "ENTITY_INVALID"); entities.set(eid, String(e.kind)); }
  const actorIds = new Set([...entities].filter(([, k]) => k === "ACTOR").map(([v]) => v));
  const rows = (name: string) => { const list = value[name]; if (!Array.isArray(list)) fail("RUNTIME_CONTRACT_INVALID", name); return list as unknown[]; };
  const policies = rows("actorPolicies").map(v => object(v, "POLICY_INVALID")); const policyIds = new Set(policies.map(v => id(v.id, "policy.id"))); unique([...policyIds], "policies");
  const capabilityRows = rows("capabilities").map(v => object(v, "CAPABILITY_INVALID")); const capabilityIds = new Set(capabilityRows.map(v => id(v.id, "capability.id"))); unique([...capabilityIds], "capabilities");
  policies.forEach(p => { exact(p, ["id", "actorId", "capabilityIds"], "POLICY_INVALID"); const aid = id(p.actorId, "policy.actorId"); if (!actorIds.has(aid)) fail("RUNTIME_CONTRACT_DANGLING_ACTOR", aid); strings(p.capabilityIds, "policy.capabilityIds").forEach(c => { if (!capabilityIds.has(c)) fail("RUNTIME_CONTRACT_DANGLING_CAPABILITY", c); }); });
  capabilityRows.forEach(c => { exact(c, ["id", "institutionId", "allowedActorIds", "effectTemplates"], "CAPABILITY_INVALID"); const institution = id(c.institutionId, "capability.institutionId"); if (entities.get(institution) !== "INSTITUTION") fail("RUNTIME_CONTRACT_REFERENCE_KIND", `institutionId.${institution}`); strings(c.allowedActorIds, "capability.allowedActorIds").forEach(a => { if (!actorIds.has(a)) fail("RUNTIME_CONTRACT_DANGLING_ACTOR", a); }); if (!Array.isArray(c.effectTemplates)) fail("CAPABILITY_INVALID", "effectTemplates"); c.effectTemplates.forEach(p => validateDurablePredicate(p, entities, capabilityIds)); });
  const projections = rows("openingProjections").map(v => object(v, "PROJECTION_INVALID")); const projectionIds = new Set(projections.map(p => id(p.id, "projection.id"))); unique([...projectionIds], "projections");
  rows("roles").forEach(raw => { const r = object(raw, "ROLE_INVALID"); exact(r, ["id", "actorId", "goalIds", "secretIds", "destinyQuestion", "openingProjectionId", "policyId"], "ROLE_INVALID"); id(r.id, "role.id"); const aid=id(r.actorId,"role.actorId"); if(!actorIds.has(aid)) fail("RUNTIME_CONTRACT_DANGLING_ACTOR",aid); strings(r.goalIds,"role.goalIds"); strings(r.secretIds,"role.secretIds").forEach(s=>{if(entities.get(s)!=="SECRET") fail("RUNTIME_CONTRACT_REFERENCE_KIND",`secretId.${s}`)}); if(!projectionIds.has(String(r.openingProjectionId))) fail("RUNTIME_CONTRACT_DANGLING_PROJECTION",String(r.openingProjectionId)); if(!policyIds.has(String(r.policyId))) fail("RUNTIME_CONTRACT_DANGLING_POLICY",String(r.policyId)); });
  rows("knowledgeAcl").forEach(raw => { const a=object(raw,"ACL_INVALID"); exact(a,["id","secretId","actorIds","visibility"],"ACL_INVALID"); id(a.id,"acl.id"); const secret=id(a.secretId,"acl.secretId"); if(entities.get(secret)!=="SECRET") fail("RUNTIME_CONTRACT_REFERENCE_KIND",`secretId.${secret}`); const grants=strings(a.actorIds,"acl.actorIds"); grants.forEach(x=>{if(!actorIds.has(x)) fail("RUNTIME_CONTRACT_DANGLING_ACTOR",x)}); const vis=validateVisibility(a.visibility,actorIds,policyIds); if(vis.scope==="PUBLIC" || vis.scope==="INFERABLE") fail("ACL_LEAK",secret); if(vis.scope==="PRIVATE" && (grants.length!==1 || grants[0]!==vis.actorId)) fail("ACL_LEAK",secret); if(vis.scope==="ACTOR_SET" && (new Set([...grants,...vis.actorIds]).size!==grants.length || vis.actorIds.length!==grants.length)) fail("ACL_LEAK",secret); });
  const validateRule = (raw: unknown, delayed: boolean) => { const r=object(raw,"RULE_INVALID"); exact(r,["id","capabilityId",...(r.condition===undefined?[]:["condition"]),"effects","visibility",...(delayed?["delayRevisions"]:[])],"RULE_INVALID"); id(r.id,"rule.id"); if(!capabilityIds.has(String(r.capabilityId))) fail("RUNTIME_CONTRACT_DANGLING_CAPABILITY",String(r.capabilityId)); if(r.condition) validateCondition(r.condition,entities,capabilityIds); if(!Array.isArray(r.effects)||!r.effects.length) fail("RULE_INVALID","effects"); r.effects.forEach(p=>validateDurablePredicate(p,entities,capabilityIds)); validateVisibility(r.visibility,actorIds,policyIds); if(delayed && (!Number.isInteger(r.delayRevisions)||Number(r.delayRevisions)<1)) fail("RULE_INVALID","delayRevisions"); return id(r.id,"rule.id"); };
  const allRuleRows=[...rows("causalRules"),...rows("delayedRules")].map(r=>object(r,"RULE_INVALID"));
  const ruleIds=[...rows("causalRules").map(r=>validateRule(r,false)),...rows("delayedRules").map(r=>validateRule(r,true))]; unique(ruleIds,"rules"); const ruleSet=new Set(ruleIds);
  rows("destinyHooks").forEach(raw=>{const h=object(raw,"HOOK_INVALID"); exact(h,["id","actorIds","entityIds","secretIds","causalRuleIds","activationCondition",...(h.convergenceCondition===undefined?[]:["convergenceCondition"]),...(h.resolutionCondition===undefined?[]:["resolutionCondition"])],"HOOK_INVALID"); id(h.id,"hook.id"); strings(h.actorIds,"hook.actorIds").forEach(a=>{if(!actorIds.has(a))fail("RUNTIME_CONTRACT_DANGLING_ACTOR",a)}); strings(h.entityIds,"hook.entityIds").forEach(e=>{if(!entities.has(e))fail("RUNTIME_CONTRACT_DANGLING_ENTITY",e)}); strings(h.secretIds,"hook.secretIds").forEach(e=>{if(entities.get(e)!=="SECRET")fail("RUNTIME_CONTRACT_REFERENCE_KIND",e)}); strings(h.causalRuleIds,"hook.causalRuleIds").forEach(r=>{if(!ruleSet.has(r))fail("RUNTIME_CONTRACT_DANGLING_RULE",r)}); validateCondition(h.activationCondition,entities,capabilityIds); if(h.convergenceCondition)validateCondition(h.convergenceCondition,entities,capabilityIds); if(h.resolutionCondition)validateCondition(h.resolutionCondition,entities,capabilityIds); });
  const state=object(value.openingState,"STATE_INVALID"); exact(state,["worldId","revision","predicates","pendingRuleIds"],"STATE_INVALID"); if(state.worldId!==worldId)fail("RUNTIME_CONTRACT_WORLD_MISMATCH",String(state.worldId)); if(state.revision!==0)fail("STATE_REVISION_INVALID",String(state.revision)); if(!Array.isArray(state.predicates))fail("STATE_INVALID","predicates"); state.predicates.forEach(p=>validateDurablePredicate(p,entities,capabilityIds)); strings(state.pendingRuleIds,"state.pendingRuleIds").forEach(r=>{if(!new Set(rows("delayedRules").map(x=>String(object(x,"RULE_INVALID").id))).has(r))fail("RUNTIME_CONTRACT_DANGLING_RULE",r)});
  const initial=new Set((state.predicates as DurablePredicate[]).map(p=>JSON.stringify(p))), providers=new Map<string,string[]>(); allRuleRows.forEach(r=>(r.effects as DurablePredicate[]).forEach(p=>{const key=JSON.stringify(p),list=providers.get(key)??[];list.push(String(r.id));providers.set(key,list)}));
  const graph=new Map<string,string[]>(); for(const rule of allRuleRows){const deps=new Set<string>(); if(rule.condition){for(const predicate of predicatesFromCondition(rule.condition as CausalCondition)){const key=JSON.stringify(predicate);if(initial.has(key))continue;const sources=providers.get(key);if(!sources?.length)fail("CAUSAL_REFERENCE_UNSATISFIABLE",`${String(rule.id)}.${key}`);sources.forEach(s=>deps.add(s));}}graph.set(String(rule.id),[...deps]);}
  const visiting=new Set<string>(),visited=new Set<string>(); const visit=(node:string)=>{if(visiting.has(node))fail("CAUSAL_REFERENCE_CYCLE",node);if(visited.has(node))return;visiting.add(node);(graph.get(node)??[]).forEach(visit);visiting.delete(node);visited.add(node)};[...graph.keys()].forEach(visit);
  projections.forEach(p=>{exact(p,["id","actorId","visibleEntityIds","knownSecretIds","visiblePredicates"],"PROJECTION_INVALID"); const aid=id(p.actorId,"projection.actorId"); if(!actorIds.has(aid))fail("RUNTIME_CONTRACT_DANGLING_ACTOR",aid); const visible=new Set(strings(p.visibleEntityIds,"projection.visibleEntityIds")); visible.forEach(e=>{if(!entities.has(e))fail("RUNTIME_CONTRACT_DANGLING_ENTITY",e)}); strings(p.knownSecretIds,"projection.knownSecretIds").forEach(s=>{if(entities.get(s)!=="SECRET")fail("RUNTIME_CONTRACT_REFERENCE_KIND",s); const grant=rows("knowledgeAcl").map(x=>object(x,"ACL_INVALID")).find(x=>x.secretId===s); if(!grant||!strings(grant.actorIds,"acl.actorIds").includes(aid))fail("ACL_LEAK",`${aid}.${s}`)}); if(!Array.isArray(p.visiblePredicates))fail("PROJECTION_INVALID","visiblePredicates"); p.visiblePredicates.forEach(x=>{const predicate=validateDurablePredicate(x,entities,capabilityIds); for(const [k,v] of Object.entries(predicate)) if(k.endsWith("Id")&&entities.has(String(v))&&!visible.has(String(v))&&entities.get(String(v))!=="SECRET")fail("ACL_LEAK",`${aid}.${String(v)}`)}); });
  const style=object(value.styleProfile,"STYLE_INVALID"); exact(style,["locale","pov","tense","tags"],"STYLE_INVALID"); if(typeof style.locale!=="string"||!["FIRST_PERSON","SECOND_PERSON","THIRD_PERSON_LIMITED"].includes(String(style.pov))||!["PAST","PRESENT"].includes(String(style.tense)))fail("STYLE_INVALID","enum"); strings(style.tags,"style.tags");
  return value as WorldRuntimeContract;
}

export function conditionSatisfied(condition: CausalCondition | undefined, predicates: DurablePredicate[]): boolean {
  if (!condition) return true; const has=(needle:DurablePredicate)=>predicates.some(p=>JSON.stringify(p)===JSON.stringify(needle));
  return "all" in condition ? condition.all.every(has) : "any" in condition ? condition.any.some(has) : !has(condition.not);
}

export function validateCausalEvent(input: unknown, contractInput: WorldRuntimeContract): CausalEvent {
  const contract=validateWorldRuntimeContract(contractInput), value=object(input,"CAUSAL_EVENT_INVALID"); exact(value,["eventId","worldId","sourceRuleId","originActorId","affectedActorIds","predicate","status","createdAtRevision",...(value.applyAtRevision===undefined?[]:["applyAtRevision"]),"visibility","idempotencyKey"],"CAUSAL_EVENT_INVALID");
  id(value.eventId,"event.eventId"); if(value.worldId!==contract.worldId)fail("RUNTIME_CONTRACT_WORLD_MISMATCH",String(value.worldId)); const rules=new Set([...contract.causalRules,...contract.delayedRules].map(r=>r.id)); if(!rules.has(String(value.sourceRuleId)))fail("RUNTIME_CONTRACT_DANGLING_RULE",String(value.sourceRuleId));
  const entities=new Map(contract.entities.map(e=>[e.id,e.kind])); const actors=new Set(contract.entities.filter(e=>e.kind==="ACTOR").map(e=>e.id)), policies=new Set(contract.actorPolicies.map(p=>p.id)), capabilities=new Set(contract.capabilities.map(c=>c.id)); if(!actors.has(String(value.originActorId)))fail("RUNTIME_CONTRACT_DANGLING_ACTOR",String(value.originActorId)); strings(value.affectedActorIds,"event.affectedActorIds").forEach(a=>{if(!actors.has(a))fail("RUNTIME_CONTRACT_DANGLING_ACTOR",a)}); validateDurablePredicate(value.predicate,entities,capabilities); if(!["SCHEDULED","APPLIED","CANCELLED"].includes(String(value.status)))fail("CAUSAL_EVENT_INVALID","status"); if(!Number.isInteger(value.createdAtRevision)||Number(value.createdAtRevision)<0)fail("STATE_REVISION_INVALID",String(value.createdAtRevision)); if(value.applyAtRevision!==undefined&&(!Number.isInteger(value.applyAtRevision)||Number(value.applyAtRevision)<=Number(value.createdAtRevision)))fail("STATE_REVISION_INVALID",String(value.applyAtRevision)); validateVisibility(value.visibility,actors,policies); if(typeof value.idempotencyKey!=="string"||!value.idempotencyKey)fail("CAUSAL_EVENT_INVALID","idempotencyKey"); return value as CausalEvent;
}

export function validateDurableTurnEnvelope(input: unknown, contractInput: WorldRuntimeContract): DurableTurnEnvelope {
  const contract=validateWorldRuntimeContract(contractInput), value=object(input,"TURN_ENVELOPE_INVALID"); exact(value,["id","worldId","beforeStateRevision","sourceRuleId","originActorId","allowedPredicates","requiredVisiblePredicates","forbiddenPredicates","events","projectionActorId"],"TURN_ENVELOPE_INVALID"); id(value.id,"envelope.id"); if(value.worldId!==contract.worldId)fail("RUNTIME_CONTRACT_WORLD_MISMATCH",String(value.worldId)); if(!Number.isInteger(value.beforeStateRevision)||Number(value.beforeStateRevision)<0)fail("STATE_REVISION_INVALID",String(value.beforeStateRevision));
  const entities=new Map(contract.entities.map(e=>[e.id,e.kind])), capabilities=new Set(contract.capabilities.map(c=>c.id)), actors=new Set(contract.entities.filter(e=>e.kind==="ACTOR").map(e=>e.id)), rules=new Set([...contract.causalRules,...contract.delayedRules].map(r=>r.id)); if(!rules.has(String(value.sourceRuleId)))fail("RUNTIME_CONTRACT_DANGLING_RULE",String(value.sourceRuleId)); for(const key of ["originActorId","projectionActorId"])if(!actors.has(String(value[key])))fail("RUNTIME_CONTRACT_DANGLING_ACTOR",String(value[key]));
  const groups=["allowedPredicates","requiredVisiblePredicates","forbiddenPredicates"] as const; const encoded=new Map<string,string>(); for(const group of groups){if(!Array.isArray(value[group]))fail("TURN_ENVELOPE_INVALID",group);for(const raw of value[group] as unknown[]){const p=validateDurablePredicate(raw,entities,capabilities), key=JSON.stringify(p), prior=encoded.get(key);if(prior&&prior!==group)fail("TURN_ENVELOPE_CONTRADICTION",`${prior}.${group}`);encoded.set(key,group);}}
  if(!Array.isArray(value.events))fail("TURN_ENVELOPE_INVALID","events"); const events=(value.events as unknown[]).map(e=>validateCausalEvent(e,contract)); unique(events.map(e=>e.eventId),"events"); return value as DurableTurnEnvelope;
}
