export const PRESSURE_CHAPTER_CONTRACT_ERROR_CODES = {
  CANONICAL_JSON_UNSUPPORTED: "CANONICAL_JSON_UNSUPPORTED",
  CANONICAL_JSON_CYCLE: "CANONICAL_JSON_CYCLE",
  CONTRACT_NOT_OBJECT: "CONTRACT_NOT_OBJECT",
  CONTRACT_UNKNOWN_FIELD: "CONTRACT_UNKNOWN_FIELD",
  CONTRACT_MISSING_FIELD: "CONTRACT_MISSING_FIELD",
  CONTRACT_FIELD_INVALID: "CONTRACT_FIELD_INVALID",
  CONTRACT_DUPLICATE_VALUE: "CONTRACT_DUPLICATE_VALUE",
  CONTRACT_ORDER_INVALID: "CONTRACT_ORDER_INVALID",
  CONTRACT_HASH_MISMATCH: "CONTRACT_HASH_MISMATCH",
  CONTRACT_REFERENCE_MISMATCH: "CONTRACT_REFERENCE_MISMATCH",
  CONTRACT_SEQUENCE_MISMATCH: "CONTRACT_SEQUENCE_MISMATCH",
  CONTRACT_FINGERPRINT_MISMATCH: "CONTRACT_FINGERPRINT_MISMATCH",
  SCHEMA_VERSION_UNSUPPORTED: "SCHEMA_VERSION_UNSUPPORTED",
  RUN_ROUTE_INCOMPLETE: "RUN_ROUTE_INCOMPLETE",
  RUN_ROUTE_UNREGISTERED: "RUN_ROUTE_UNREGISTERED",
  RUN_ROUTE_HASH_MISMATCH: "RUN_ROUTE_HASH_MISMATCH",
  RUNTIME_PROFILE_UNSUPPORTED: "RUNTIME_PROFILE_UNSUPPORTED",
  ENDGAME_POLICY_MISMATCH: "ENDGAME_POLICY_MISMATCH",
  RESULT_SCHEMA_UNSUPPORTED: "RESULT_SCHEMA_UNSUPPORTED",
  CONTENT_PACKAGE_HASH_MISMATCH: "CONTENT_PACKAGE_HASH_MISMATCH",
  ORCHESTRATION_PACKAGE_HASH_MISMATCH: "ORCHESTRATION_PACKAGE_HASH_MISMATCH",
  RUNTIME_CONTRACT_HASH_MISMATCH: "RUNTIME_CONTRACT_HASH_MISMATCH",
  TEST_MATRIX_HASH_MISMATCH: "TEST_MATRIX_HASH_MISMATCH",
  CONTROL_TOPOLOGY_HASH_MISMATCH: "CONTROL_TOPOLOGY_HASH_MISMATCH",
  ROUTE_HANDLER_MISMATCH: "ROUTE_HANDLER_MISMATCH",
  ROUTE_REGISTRY_INVALID: "ROUTE_REGISTRY_INVALID",
  ROUTE_REGISTRY_DUPLICATE: "ROUTE_REGISTRY_DUPLICATE",
  ROUTE_REGISTRY_HASH_MISMATCH: "ROUTE_REGISTRY_HASH_MISMATCH",
  CHAPTER_SETTLEMENT_FINGERPRINT_MISMATCH:
    "CHAPTER_SETTLEMENT_FINGERPRINT_MISMATCH",
} as const;

export type PressureChapterContractErrorCode =
  (typeof PRESSURE_CHAPTER_CONTRACT_ERROR_CODES)[keyof typeof PRESSURE_CHAPTER_CONTRACT_ERROR_CODES];

export class PressureChapterContractError extends Error {
  readonly code: PressureChapterContractErrorCode;
  readonly path: string;
  readonly detail: string | undefined;

  constructor(
    code: PressureChapterContractErrorCode,
    path: string,
    detail?: string,
  ) {
    super(`${code}:${path}${detail ? `:${detail}` : ""}`);
    this.name = "PressureChapterContractError";
    this.code = code;
    this.path = path;
    this.detail = detail;
  }
}

export function failPressureContract(
  code: PressureChapterContractErrorCode,
  path: string,
  detail?: string,
): never {
  throw new PressureChapterContractError(code, path, detail);
}
