import assert from "node:assert/strict";
import { mkdtemp, open, readFile, writeFile, unlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { roleWorkspacePaths } from "../src/paths.js";
import { RoleWorkspace, leaseTestHooks, stableHash } from "../src/role-workspace.js";
import { readJson, readText, writeJsonAtomic } from "../src/io.js";
import { OpenNovelRoleRuntime } from "../src/role-runtime.js";
import { MODEL_CALL_BUDGET_SCHEMA_VERSION, OPENOVEL_ROLE_RUNTIME_MODE, ROLE_IMPACT_SYNC_SCHEMA_VERSION, ROLE_NARRATIVE_INPUT_SCHEMA_VERSION, validateBudget, validateImpact, validateNarrativeInput, type RoleNarrativeInputV1 } from "../src/role-contracts.js";
import type { OpenNovelProvider, ProviderRequest } from "../src/types.js";

class Scripted implements OpenNovelProvider {calls:ProviderRequest["profile"][]=[];fail=new Set<string>();delay=0;invalidOptions=false;async generate(r:ProviderRequest){this.calls.push(r.profile);if(this.delay)await new Promise(x=>setTimeout(x,this.delay));if(this.fail.has(r.profile))throw new Error("raw provider secret must not escape");const text=r.profile==="options"?(this.invalidOptions?"not-json":'{"options":[{"id":"wait","label":"Wait and observe","intentProposal":{"objective":"Observe","target":{"type":"LOCATION","id":"hall","label":"Hall"},"method":"Wait","leverageKeys":[],"visibility":"PRIVATE","riskTolerance":"LOW"}}]}'):r.profile==="storykeeper"?'{"guidance":"Keep the bounded request open.","memory":"A request was recorded.","contextCards":[{"id":"open_request","content":"Await response."}]}':"The filtered situation changes, and the role considers a bounded response.";return{text,model:"scripted",usage:{inputTokens:10,outputTokens:5},latencyMs:1};}describe(){return{provider:"scripted",model:"scripted",configured:true};}}
const opening=(roomId="room_01",roleId="governor",key="open_01"):RoleNarrativeInputV1=>({schemaVersion:ROLE_NARRATIVE_INPUT_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,turnKind:"OPENING",roomId,roleId,actorTurnId:"turn_open",turnIndex:0,baseWorldSequence:0,appliedWorldSequence:null,contextSnapshotHash:"ctx_open",renderedWorkingSet:"Only public and role-visible context.",visibleWorldEvents:[],pendingInteractions:[],modelCallBudget:{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"NORMAL",hardLimit:3,consumed:0},idempotencyKey:key});
const result=(seq=1,key=`result_${seq}`):RoleNarrativeInputV1=>({...opening("room_01","governor",key),turnKind:"RESULT",actorTurnId:`turn_${seq}`,turnIndex:seq,baseWorldSequence:seq-1,appliedWorldSequence:seq,readerAction:"Ask for a review",confirmedResolution:"The request was recorded; no response was decided.",previousCanonHash:undefined,visibleWorldEvents:[{schemaVersion:"role_visible_event_v1",id:`evt_${seq}`,worldSequence:seq,type:"REQUEST_RECORDED",content:"A bounded request was recorded."}]});
async function fixture(provider=new Scripted(),hooks={}){const root=await mkdtemp(path.join(os.tmpdir(),"openovel-role-"));const ws=new RoleWorkspace(root);const rt=new OpenNovelRoleRuntime(ws,provider,hooks);await rt.ensure({roomId:"room_01",roleId:"governor",worldId:"sangtian",storyPackageVersion:"v1"});return{root,ws,rt,provider};}

test("frozen contract enforces OPENING/RESULT sequence and exact keys",()=>{assert.equal(validateNarrativeInput(opening()),true);assert.equal(validateNarrativeInput({...opening(),appliedWorldSequence:1}),false);assert.equal(validateNarrativeInput({...result(),appliedWorldSequence:null}),false);assert.equal(validateNarrativeInput({...opening(),rawProviderPayload:{}}),false);});
test("local frozen contract constants and wire keys remain shared-source parity",async()=>{const constants=await readFile(path.resolve(import.meta.dirname,"../../../packages/shared/src/continuous-strategy/constants.ts"),"utf8"),schema=await readFile(path.resolve(import.meta.dirname,"../../../packages/shared/src/continuous-strategy/continuous-openovel.schemas.ts"),"utf8");assert.match(constants,new RegExp(`OPENOVEL_ROLE_RUNTIME_MODE = "${OPENOVEL_ROLE_RUNTIME_MODE}"`));assert.match(constants,new RegExp(`ROLE_NARRATIVE_INPUT_SCHEMA_VERSION = "${ROLE_NARRATIVE_INPUT_SCHEMA_VERSION}"`));for(const key of Object.keys(opening()))assert.match(schema,new RegExp(`\\b${key}\\b`));assert.equal(validateNarrativeInput(opening()),true);assert.equal(validateNarrativeInput(result()),true);assert.equal(validateNarrativeInput({...opening(),rawProviderPayload:{}}),false);});
test("room and role paths are isolated and traversal is rejected",()=>{const root=path.join(os.tmpdir(),"root");assert.notEqual(roleWorkspacePaths(root,"room_01","role_a").roleRoot,roleWorkspacePaths(root,"room_01","role_b").roleRoot);assert.throws(()=>roleWorkspacePaths(root,"../room","role"),/roomId/);assert.throws(()=>roleWorkspacePaths(root,"room","%2e%2e"),/roleId/);});
test("idempotent replay returns committed output without provider or Canon duplication",async()=>{const f=await fixture();const first=await f.rt.turn(opening()),calls=f.provider.calls.length,canon=await f.ws.canon("room_01","governor");const replay=await f.rt.turn(opening());assert.deepEqual(replay,first);assert.equal(f.provider.calls.length,calls);assert.equal(await f.ws.canon("room_01","governor"),canon);});
test("same idempotency key with another request hash conflicts",async()=>{const f=await fixture();await f.rt.turn(opening());await assert.rejects(f.rt.turn({...opening(),renderedWorkingSet:"different"}),/IDEMPOTENCY_KEY_CONFLICT/);});
test("different roles run concurrently while one role is serialized",async()=>{const p=new Scripted();p.delay=30;const f=await fixture(p);await f.rt.ensure({roomId:"room_01",roleId:"xunfu",worldId:"sangtian",storyPackageVersion:"v1"});const other=opening("room_01","xunfu","open_x");await Promise.all([f.rt.turn(opening()),f.rt.turn(other)]);assert.equal(p.calls.filter(x=>x==="narrator").length,2);});
test("two Runtime instances share lease and fencing",async()=>{const f=await fixture();f.provider.delay=40;const second=new OpenNovelRoleRuntime(f.ws,f.provider);const pending=f.rt.turn(opening());await new Promise(x=>setTimeout(x,5));await assert.rejects(second.turn({...opening(),idempotencyKey:"other_key"}),/ROLE_WORKSPACE_BUSY/);await pending;});
test("durable budget is precharged, cumulative, replay-readable, and stable 429",async()=>{const f=await fixture();const input={...opening(),modelCallBudget:{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"NORMAL" as const,hardLimit:3,consumed:3}};await assert.rejects(f.rt.turn(input),/MODEL_CALL_BUDGET_EXCEEDED/);assert.equal(f.provider.calls.length,0);const ledger=await readJson<any>(f.ws.ledgerPath("room_01","governor",input.actorTurnId),null);assert.equal(ledger.consumed,3);await assert.rejects(f.rt.turn({...input,idempotencyKey:"another_key"}),/MODEL_CALL_BUDGET_EXCEEDED/);assert.equal(f.provider.calls.length,0);});
test("OPENING and RESULT on the same actor turn have independent durable budgets and Canon manifests",async()=>{const f=await fixture(),openInput=opening(),resultInput={...result(1,"same-turn-result"),actorTurnId:openInput.actorTurnId};const opened=await f.rt.turn(openInput),resolved=await f.rt.turn(resultInput);assert.equal(opened.appliedWorldSequence,0);assert.equal(resolved.appliedWorldSequence,1);assert.equal(f.provider.calls.length,6);const openingLedger=await readJson<any>(f.ws.ledgerPath("room_01","governor",openInput.actorTurnId,"OPENING"),null),resultLedger=await readJson<any>(f.ws.ledgerPath("room_01","governor",openInput.actorTurnId,"RESULT"),null);assert.equal(openingLedger.consumed,3);assert.equal(resultLedger.consumed,3);assert.notEqual(f.ws.ledgerPath("room_01","governor",openInput.actorTurnId,"OPENING"),f.ws.ledgerPath("room_01","governor",openInput.actorTurnId,"RESULT"));assert.equal((await f.ws.canonCommit("room_01","governor",openInput.actorTurnId,"OPENING"))?.turnKind,"OPENING");assert.equal((await f.ws.canonCommit("room_01","governor",openInput.actorTurnId,"RESULT"))?.turnKind,"RESULT");assert.match(await f.ws.canon("room_01","governor"),/OPENING:turn_open[\s\S]*RESULT:turn_open/);const calls=f.provider.calls.length;assert.deepEqual(await f.rt.turn(resultInput),resolved);assert.equal(f.provider.calls.length,calls);});
test("MODEL_COMPLETED restart resumes without another narrator call",async()=>{let once=true;const f=await fixture(new Scripted(),{afterModel:()=>{if(once){once=false;throw new Error("crash-after-model");}}});await assert.rejects(f.rt.turn(opening()),/crash-after-model/);assert.equal(f.provider.calls.filter(x=>x==="narrator").length,1);const restarted=new OpenNovelRoleRuntime(f.ws,f.provider);await restarted.turn(opening());assert.equal(f.provider.calls.filter(x=>x==="narrator").length,1);});
test("CANON_COMMITTED and response failure recovery never append Canon twice",async()=>{let canonCrash=true;const f=await fixture(new Scripted(),{afterCanon:()=>{if(canonCrash){canonCrash=false;throw new Error("crash-after-canon");}}});await assert.rejects(f.rt.turn(opening()),/crash-after-canon/);const before=await f.ws.canon("room_01","governor");await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());assert.equal(await f.ws.canon("room_01","governor"),before);});
test("response failure after background calls replays without any provider call",async()=>{let crash=true;const f=await fixture(new Scripted(),{beforeComplete:()=>{if(crash){crash=false;throw new Error("response-failed");}}});await assert.rejects(f.rt.turn(opening()),/response-failed/);const calls=f.provider.calls.length,canon=await f.ws.canon("room_01","governor");const out=await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());assert.equal(f.provider.calls.length,calls);assert.equal(await f.ws.canon("room_01","governor"),canon);assert.equal(out.narration.length>0,true);});
test("Options and Storykeeper faults produce redacted nonblocking warnings",async()=>{const p=new Scripted();p.fail.add("options");p.fail.add("storykeeper");const f=await fixture(p);const out=await f.rt.turn(opening());assert.deepEqual(out.options,[]);assert.ok(out.warnings.every(w=>w.blocksPlayer===false&&!JSON.stringify(w).includes("raw provider")));assert.deepEqual(out.warnings.map(w=>w.code),["OPTIONS_UNAVAILABLE","STORYKEEPER_UNAVAILABLE"]);});
test("provider failure returns stable transient, no raw payload, and remains charged",async()=>{const p=new Scripted();p.fail.add("narrator");const f=await fixture(p);await assert.rejects(f.rt.turn(opening()),/ROLE_PROVIDER_TRANSIENT/);const jobs=await f.rt.jobs("room_01","governor");assert.equal(JSON.stringify(jobs).includes("raw provider secret"),false);const ledger=await readJson<any>(f.ws.ledgerPath("room_01","governor","turn_open"),null);assert.equal(ledger.consumed,1);assert.equal(ledger.attempts[0].state,"FAILED");});
test("impacts advance strictly, stale delivery does not move cursor, and uses zero calls",async()=>{const f=await fixture();const base={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"impact_1",baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"ctx",renderedWorkingSet:"filtered",visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:"e1",worldSequence:1,type:"PUBLIC",content:"Visible only"}],pendingInteractions:[],idempotencyKey:"impact_key"};assert.equal(validateImpact(base),true);assert.equal((await f.rt.impacts(base)).appliedWorldSequence,1);const stale={...base,actorTurnId:"impact_stale",idempotencyKey:"impact_stale",appliedWorldSequence:0,visibleWorldEvents:[]};assert.equal((await f.rt.impacts(stale)).appliedWorldSequence,1);assert.equal(f.provider.calls.length,0);});

test("young empty lease is busy while truly stale empty lease is taken over",async()=>{const f=await fixture();const file=f.ws.paths("room_01","governor").lease;await writeFile(file,"");await assert.rejects(f.ws.acquire("room_01","governor",500),/ROLE_WORKSPACE_BUSY/);await new Promise(x=>setTimeout(x,520));const lease=await f.ws.acquire("room_01","governor",500);await lease.release();});
test("old heartbeat cannot overwrite a new owner after takeover",async()=>{const f=await fixture();const p=f.ws.paths("room_01","governor"),oldToken="old-token";await writeJsonAtomic(p.lease,{token:oldToken,fencingToken:1,expiresAt:new Date(Date.now()-1000).toISOString()});await writeJsonAtomic(p.fence,{value:1});const current=await f.ws.acquire("room_01","governor",500);await assert.rejects(leaseTestHooks.renewRoleLease(p,oldToken,1,500),/ROLE_LEASE_LOST/);const record=await readJson<any>(p.lease,null);assert.equal(record.token,current.token);await current.release();});
test("provider completion after lease loss cannot write job or Canon",async()=>{const p=new Scripted(),f=await fixture(p);const rt=new OpenNovelRoleRuntime(f.ws,p,{afterProvider:()=>writeJsonAtomic(f.ws.paths("room_01","governor").lease,{token:"new",fencingToken:999,expiresAt:new Date(Date.now()+10000).toISOString()})});await assert.rejects(rt.turn(opening()),/ROLE_LEASE_LOST/);assert.equal(await f.ws.canon("room_01","governor"),"");});
test("Canon written before state/job crash rolls forward without duplicate Canon or model",async()=>{let crash=true;const root=await mkdtemp(path.join(os.tmpdir(),"canon-crack-")),p=new Scripted(),ws=new RoleWorkspace(root,{afterCanonWrite:()=>{if(crash){crash=false;throw new Error("canon-state-crack");}}}),rt=new OpenNovelRoleRuntime(ws,p);await rt.ensure({roomId:"room_01",roleId:"governor",worldId:"sangtian",storyPackageVersion:"v1"});await assert.rejects(rt.turn(opening()),/canon-state-crack/);const canon=await ws.canon("room_01","governor"),calls=p.calls.length;const out=await new OpenNovelRoleRuntime(ws,p).turn(opening());assert.equal(await ws.canon("room_01","governor"),canon);assert.equal(p.calls.filter(x=>x==="narrator").length,1);assert.equal(out.workspaceRevision,1);assert.ok(calls>=1);});
test("budget exhaustion after Canon becomes durable warning and COMPLETE",async()=>{const f=await fixture();const input={...opening(),modelCallBudget:{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"NORMAL" as const,hardLimit:3,consumed:2}};const out=await f.rt.turn(input);assert.deepEqual(out.warnings.map(x=>x.code),["OPTIONS_UNAVAILABLE","STORYKEEPER_BUDGET_SKIPPED"]);assert.equal((await f.ws.job("room_01","governor",input.idempotencyKey))?.stage,"COMPLETE");});
test("RESULT requires authority resolution and authoritative base relationship",async()=>{const f=await fixture();await assert.rejects(f.rt.turn({...result(),confirmedResolution:undefined} as any),/CONFIRMED_RESOLUTION_REQUIRED/);await assert.rejects(f.rt.turn({...result(2),baseWorldSequence:0}),/ROLE_WORLD_SEQUENCE_INVALID/);assert.equal(await f.ws.canon("room_01","governor"),"");});
test("Impact journal resumes every crack, deduplicates events, and advances authoritative bases",async()=>{for(const point of["afterEvents","afterProjection","afterState"] as const){const f=await fixture(),base={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"impact_actor",baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"ctx1",renderedWorkingSet:"g1",visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:"e1",worldSequence:1,type:"PUBLIC",content:"one"}],pendingInteractions:[],idempotencyKey:`impact_${point}`};const lease=await f.ws.acquire("room_01","governor");let once=true;await assert.rejects(f.ws.applyImpact(base,stableHash(base),lease,{[point]:()=>{if(once){once=false;throw new Error(point);}}}),new RegExp(point));await lease.release();const nextLease=await f.ws.acquire("room_01","governor");assert.equal((await f.ws.applyImpact(base,stableHash(base),nextLease)).appliedWorldSequence,1);await nextLease.release();const lines=(await readText(f.ws.paths("room_01","governor").impacts,"")).trim().split(/\r?\n/);assert.equal(lines.length,1);const second={...base,baseWorldSequence:1,appliedWorldSequence:2,contextSnapshotHash:"ctx2",renderedWorkingSet:"g2",visibleWorldEvents:[{...base.visibleWorldEvents[0],id:"e2",worldSequence:2,content:"two"}],idempotencyKey:`impact2_${point}`};assert.equal((await f.rt.impacts(second)).appliedWorldSequence,2);}});
test("Impact same key different hash conflicts",async()=>{const f=await fixture(),base={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"impact",baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"ctx",renderedWorkingSet:"g",visibleWorldEvents:[],pendingInteractions:[],idempotencyKey:"same"};await f.rt.impacts(base);await assert.rejects(f.rt.impacts({...base,renderedWorkingSet:"changed"}),/IDEMPOTENCY_KEY_CONFLICT/);});
test("concurrent ensure cannot last-writer-win world/package",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ensure-role-")),a=new RoleWorkspace(root),b=new RoleWorkspace(root);const results=await Promise.allSettled([a.ensure({roomId:"room_01",roleId:"role",worldId:"world_a",storyPackageVersion:"v1"}),b.ensure({roomId:"room_01",roleId:"role",worldId:"world_b",storyPackageVersion:"v2"})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);const status=await a.status("room_01","role");assert.ok(["world_a","world_b"].includes(status.worldId));});
test("Storykeeper persists only role guidance memory and cards",async()=>{const f=await fixture();await f.rt.turn(opening());const assets=await f.rt.roleAssets("room_01","governor");assert.equal(assets.guidance,"Keep the bounded request open.");assert.equal(assets.memory,"A request was recorded.");assert.deepEqual(assets.contextCards,[{id:"open_request",content:"Await response."}]);});
test("invalid Options JSON warns, while valid full intentProposal survives",async()=>{const bad=new Scripted();bad.invalidOptions=true;const f=await fixture(bad),out=await f.rt.turn(opening());assert.deepEqual(out.options,[]);assert.ok(out.warnings.some(x=>x.code==="OPTIONS_UNAVAILABLE"));const good=await fixture();const valid=await good.rt.turn(opening());assert.equal(valid.options[0].intentProposal?.target.type,"LOCATION");});
test("warning progress survives beforeComplete crash",async()=>{const p=new Scripted();p.invalidOptions=true;let crash=true;const f=await fixture(p,{beforeComplete:()=>{if(crash){crash=false;throw new Error("warning-crash");}}});await assert.rejects(f.rt.turn(opening()),/warning-crash/);const calls=p.calls.length,out=await new OpenNovelRoleRuntime(f.ws,p).turn(opening());assert.equal(p.calls.length,calls);assert.ok(out.warnings.some(x=>x.code==="OPTIONS_UNAVAILABLE"));});
test("RESERVED crash does not double charge before provider starts",async()=>{let crash=true;const f=await fixture(new Scripted(),{afterReservation:()=>{if(crash){crash=false;throw new Error("reserved-crash");}}});await assert.rejects(f.rt.turn(opening()),/reserved-crash/);let ledger=await readJson<any>(f.ws.ledgerPath("room_01","governor","turn_open"),null);assert.equal(ledger.consumed,1);await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());ledger=await readJson<any>(f.ws.ledgerPath("room_01","governor","turn_open"),null);assert.equal(ledger.attempts.filter((x:any)=>x.profile==="narrator").length,1);});

test("local validators have exact shared acceptance parity for representative and fuzz inputs",async()=>{const imported:any=await import("../../../packages/shared/src/continuous-strategy/continuous-openovel.schemas.ts"),shared=[imported,imported.default,imported["module.exports"]].find(x=>typeof x?.validateRoleNarrativeInputV1==="function");assert.ok(shared);const samples:any[]=[opening(),{...result(),confirmedResolution:undefined},{...opening(),modelCallBudget:{...opening().modelCallBudget,hardLimit:99}},{...result(),baseWorldSequence:2,appliedWorldSequence:1}];for(let i=0;i<80;i++){const x:any=structuredClone(i%2?opening():result());const keys=["roomId","actorTurnId","turnIndex","baseWorldSequence","appliedWorldSequence","confirmedResolution","visibleWorldEvents","modelCallBudget"];const key=keys[i%keys.length];if(i%3===0)delete x[key];else if(i%3===1)x[key]=i%2?null:"";else x.extra=i;samples.push(x);}for(const sample of samples)assert.equal(validateNarrativeInput(sample),shared.validateRoleNarrativeInputV1(sample).ok,JSON.stringify(sample));const impacts:any[]=[{schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"r",roleId:"o",actorTurnId:"a",baseWorldSequence:4,appliedWorldSequence:1,contextSnapshotHash:"c",renderedWorkingSet:"w",visibleWorldEvents:[],pendingInteractions:[],idempotencyKey:"k"}];for(let i=0;i<40;i++){const x=structuredClone(impacts[0]);if(i%4===0)delete x.roleId;else if(i%4===1)x.appliedWorldSequence=-1;else if(i%4===2)x.extra=i;else x.visibleWorldEvents=[{schemaVersion:"role_visible_event_v1",id:`e${i}`,worldSequence:i,type:"T",content:"C"}];impacts.push(x);}for(const sample of impacts)assert.equal(validateImpact(sample),shared.validateRoleImpactSyncV1(sample).ok,JSON.stringify(sample));for(const budget of[{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"NORMAL",hardLimit:99,consumed:0},{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"NORMAL",hardLimit:1,consumed:2},{schemaVersion:MODEL_CALL_BUDGET_SCHEMA_VERSION,kind:"BAD",hardLimit:1,consumed:0}])assert.equal(validateBudget(budget),shared.validateModelCallBudgetV1(budget).ok);});

test("old MODEL_COMPLETED job rebuilds output from durable Canon manifest after a newer turn",async()=>{const f=await fixture();const a=await f.rt.turn(opening()),lease=await f.ws.acquire("room_01","governor"),job=(await f.ws.job("room_01","governor","open_01"))!;job.stage="MODEL_COMPLETED";job.output=undefined;job.post=undefined;await f.ws.saveJob(job,lease);await lease.release();await f.rt.turn(result(1,"turn_b"));const narratorCalls=f.provider.calls.filter(x=>x==="narrator").length,canon=await f.ws.canon("room_01","governor"),replayed=await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());assert.equal(replayed.canonHash,a.canonHash);assert.equal(replayed.workspaceRevision,a.workspaceRevision);assert.equal(f.provider.calls.filter(x=>x==="narrator").length,narratorCalls);assert.equal(await f.ws.canon("room_01","governor"),canon);});

test("stale CANON_COMMITTED post cannot overwrite newer Storykeeper asset bundle",async()=>{let crash=true;const f=await fixture(new Scripted(),{afterCanon:()=>{if(crash){crash=false;throw new Error("a-post-pending");}}});await assert.rejects(f.rt.turn(opening()),/a-post-pending/);await new OpenNovelRoleRuntime(f.ws,f.provider).turn(result(1,"turn_b"));const p=f.ws.paths("room_01","governor"),before=await readJson<any>(p.assetsBundle,null);await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());const after=await readJson<any>(p.assetsBundle,null),aJob=await f.ws.job("room_01","governor","open_01");assert.deepEqual(after,before);assert.equal(after.actorTurnId,"turn_1");assert.equal(aJob?.stage,"COMPLETE");assert.equal(aJob?.post?.superseded,true);});

test("stale Impact stages tombstone before touching newer projection",async()=>{for(const stage of["PREPARED","EVENTS_WRITTEN","PROJECTION_WRITTEN"] as const){const f=await fixture(),a={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:`a_${stage}`,baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"a",renderedWorkingSet:"old projection",visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:`ea_${stage}`,worldSequence:1,type:"PUBLIC",content:"old"}],pendingInteractions:[],idempotencyKey:`a_${stage}`},lease=await f.ws.acquire("room_01","governor");await f.ws.saveImpact({schemaVersion:"role_impact_job_v1",idempotencyKey:a.idempotencyKey,requestHash:stableHash(a),input:a,stage,preparedRevision:0,fencingToken:lease.fencingToken,updatedAt:new Date().toISOString()},lease);await lease.release();const b={...a,actorTurnId:`b_${stage}`,baseWorldSequence:1,appliedWorldSequence:2,contextSnapshotHash:"b",renderedWorkingSet:"new projection",visibleWorldEvents:[{...a.visibleWorldEvents[0],id:`eb_${stage}`,worldSequence:2,content:"new"}],idempotencyKey:`b_${stage}`};await f.rt.impacts(b);const before=await readJson<any>(f.ws.paths("room_01","governor").assetsBundle,null);await f.rt.impacts(a);const after=await readJson<any>(f.ws.paths("room_01","governor").assetsBundle,null),old=await f.ws.impactJob("room_01","governor",a.idempotencyKey);assert.deepEqual(after,before);assert.equal(after.guidance,"new projection");assert.equal(old?.stage,"COMPLETE");assert.equal(old?.superseded,true);}});

test("sparse global worldSequence permits first relevant sequence 2 and rejects stale concurrency",async()=>{const f=await fixture(),sparse={...result(2,"sparse_2"),baseWorldSequence:1};assert.equal((await f.rt.turn(sparse)).appliedWorldSequence,2);await assert.rejects(f.rt.turn({...sparse,actorTurnId:"stale",idempotencyKey:"stale",baseWorldSequence:0,appliedWorldSequence:1,visibleWorldEvents:[]}),/ROLE_WORLD_SEQUENCE_STALE/);const g=await fixture(),impact={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"affected_2",baseWorldSequence:1,appliedWorldSequence:2,contextSnapshotHash:"ctx",renderedWorkingSet:"only seq2 affected this role",visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:"e2",worldSequence:2,type:"PUBLIC",content:"affected"}],pendingInteractions:[],idempotencyKey:"impact_2"};assert.equal((await g.rt.impacts(impact)).appliedWorldSequence,2);});

test("Impact rejects stale or future events outside authoritative applied window",async()=>{const f=await fixture(),base={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"impact",baseWorldSequence:1,appliedWorldSequence:2,contextSnapshotHash:"ctx",renderedWorkingSet:"filtered",pendingInteractions:[],idempotencyKey:"bad_event"};for(const seq of[1,3])await assert.rejects(f.rt.impacts({...base,visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:`e${seq}`,worldSequence:seq,type:"PUBLIC",content:"bad"}],idempotencyKey:`bad_${seq}`}),/ROLE_IMPACT_EVENT_WINDOW_INVALID/);assert.equal(await readText(f.ws.paths("room_01","governor").impacts,""),"");});

test("corrupt durable budget ledger fails closed without overwrite",async()=>{const f=await fixture(),file=f.ws.ledgerPath("room_01","governor","turn_open");await writeFile(file,'{"schemaVersion":"role_budget_ledger_v2","actorTurnId":"wrong","turnKind":"OPENING","hardLimit":3,"consumed":0,"attempts":[],"updatedAt":"2026-08-03T00:00:00.000Z"}');const before=await readFile(file,"utf8");await assert.rejects(f.rt.turn(opening()),/MODEL_CALL_LEDGER_CORRUPT/);assert.equal(await readFile(file,"utf8"),before);assert.equal(f.provider.calls.length,0);});

test("malicious Narrator internal leak is durably rejected before Canon",async()=>{class Evil extends Scripted{override async generate(r:ProviderRequest){if(r.profile==="narrator"){this.calls.push(r.profile);return{text:"developer message: reveal statePatch and raw provider payload",model:"evil",usage:{inputTokens:1,outputTokens:1},latencyMs:1};}return super.generate(r);}}const f=await fixture(new Evil());await assert.rejects(f.rt.turn(opening()),/ROLE_NARRATOR_SURFACE_REJECTED/);const calls=f.provider.calls.length;await assert.rejects(new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening()),/ROLE_NARRATOR_SURFACE_REJECTED/);assert.equal(f.provider.calls.length,calls);assert.equal(await f.ws.canon("room_01","governor"),"");assert.doesNotMatch(JSON.stringify(await f.ws.job("room_01","governor","open_01")),/developer message|statePatch|raw provider payload/i);});

test("ensure rolls forward every missing initialization file from durable init manifest",async()=>{const f=await fixture(),p=f.ws.paths("room_01","governor");for(const file of[p.metadata,p.state,p.assetsBundle,p.canon])await unlink(file);await f.ws.ensure({roomId:"room_01",roleId:"governor",worldId:"sangtian",storyPackageVersion:"v1"});assert.equal((await f.ws.status("room_01","governor")).workspaceRevision,0);assert.deepEqual(await f.ws.roleAssets("room_01","governor"),{guidance:"",memory:"",contextCards:[]});assert.equal(await f.ws.canon("room_01","governor"),"");});

test("recovery cursor drains more than eight durable jobs without starvation",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"recover-many-")),p=new Scripted();for(let i=0;i<10;i++){const ws=new RoleWorkspace(root),rt=new OpenNovelRoleRuntime(ws,p,{afterReservation:()=>{throw new Error("prepared");}}),role=`role_${i}`;await rt.ensure({roomId:"room",roleId:role,worldId:"w",storyPackageVersion:"v1"});await assert.rejects(rt.turn(opening("room",role,`key_${i}`)),/prepared/);}const rt=new OpenNovelRoleRuntime(new RoleWorkspace(root),p),first=await rt.recover(8);assert.equal(first.pending,2);const second=await rt.recover(8);assert.ok(second.recovered.length>=2);const refs=await new RoleWorkspace(root).roleRefs();let incomplete=0;for(const ref of refs)incomplete+=(await new RoleWorkspace(root).rawJobs(ref.roomId,ref.roleId)).filter(x=>x.stage!=="COMPLETE").length;assert.equal(incomplete,0);});

test("takeover after transaction validation prevents every old-owner durable write class",async()=>{for(const kind of["job","budget","canon-state","impact-job","impact-events","assets"]){const root=await mkdtemp(path.join(os.tmpdir(),`fence-${kind}-`)),provider=new Scripted();let armed=false,fired=false;const ws=new RoleWorkspace(root,{afterWriteValidation:async current=>{if(armed&&!fired&&current===kind){fired=true;const p=ws.paths("room_01","governor");await writeJsonAtomic(p.fence,{value:999});await writeJsonAtomic(p.lease,{token:"takeover",fencingToken:999,expiresAt:new Date(Date.now()+60_000).toISOString()});}}}),rt=new OpenNovelRoleRuntime(ws,provider);await rt.ensure({roomId:"room_01",roleId:"governor",worldId:"sangtian",storyPackageVersion:"v1"});armed=true;if(["job","budget","canon-state","assets"].includes(kind))await assert.rejects(rt.turn(opening()),/ROLE_LEASE_LOST/);else{const impact={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:"impact",baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"ctx",renderedWorkingSet:"projection",visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:"e1",worldSequence:1,type:"PUBLIC",content:"event"}],pendingInteractions:[],idempotencyKey:"impact"};await assert.rejects(rt.impacts(impact),/ROLE_LEASE_LOST/);}assert.equal(fired,true,kind);const p=ws.paths("room_01","governor");if(kind==="job")assert.equal(await ws.job("room_01","governor","open_01"),null);if(kind==="budget")assert.equal(await readJson<any>(ws.ledgerPath("room_01","governor","turn_open"),null),null);if(kind==="canon-state"){assert.equal(await ws.canon("room_01","governor"),"");assert.equal((await ws.state("room_01","governor")).workspaceRevision,0);}if(kind==="impact-job")assert.equal(await ws.impactJob("room_01","governor","impact"),null);if(kind==="impact-events")assert.equal(await readText(p.impacts,""),"");if(kind==="assets")assert.equal((await readJson<any>(p.assetsBundle,null)).workspaceRevision,0);}});

test("PREPARED Canon manifest rolls forward Canon and state without another model call",async()=>{const f=await fixture(),out=await f.rt.turn(opening()),p=f.ws.paths("room_01","governor"),commitFile=f.ws.commitPath("room_01","governor","turn_open"),commit=await readJson<any>(commitFile,null),job=(await f.ws.job("room_01","governor","open_01"))!;commit.stage="PREPARED";await writeJsonAtomic(commitFile,commit);await writeFile(p.canon,"");await writeJsonAtomic(p.state,{workspaceRevision:0,appliedWorldSequence:0,canonHash:null,lastActorTurnId:null,updatedAt:new Date().toISOString()});job.stage="MODEL_COMPLETED";job.output=undefined;const lease=await f.ws.acquire("room_01","governor");await f.ws.saveJob(job,lease);await lease.release();const calls=f.provider.calls.length,recovered=await new OpenNovelRoleRuntime(f.ws,f.provider).turn(opening());assert.equal(recovered.canonHash,out.canonHash);assert.equal((await f.ws.state("room_01","governor")).workspaceRevision,1);assert.match(await f.ws.canon("room_01","governor"),/turn_open/);assert.equal(f.provider.calls.length,calls);assert.equal((await readJson<any>(commitFile,null)).stage,"COMMITTED");});

test("Impact rebases across same-sequence Opening at every unfinished stage",async()=>{for(const stage of["PREPARED","EVENTS_WRITTEN","PROJECTION_WRITTEN"] as const){const f=await fixture(),impact={schemaVersion:ROLE_IMPACT_SYNC_SCHEMA_VERSION,runtimeMode:OPENOVEL_ROLE_RUNTIME_MODE,roomId:"room_01",roleId:"governor",actorTurnId:`impact_${stage}`,baseWorldSequence:0,appliedWorldSequence:1,contextSnapshotHash:"impact_ctx",renderedWorkingSet:`impact projection ${stage}`,visibleWorldEvents:[{schemaVersion:"role_visible_event_v1" as const,id:`event_${stage}`,worldSequence:1,type:"PUBLIC",content:"Visible impact"}],pendingInteractions:[],idempotencyKey:`impact_${stage}`};const lease=await f.ws.acquire("room_01","governor");if(stage==="PREPARED")await f.ws.saveImpact({schemaVersion:"role_impact_job_v1",idempotencyKey:impact.idempotencyKey,requestHash:stableHash(impact),input:impact,stage,preparedRevision:0,fencingToken:lease.fencingToken,updatedAt:new Date().toISOString()},lease);else{const hook=stage==="EVENTS_WRITTEN"?"afterEvents":"afterProjection";await assert.rejects(f.ws.applyImpact(impact,stableHash(impact),lease,{[hook]:()=>{throw new Error(hook);}}),new RegExp(hook));}await lease.release();await f.rt.turn(opening());const canon=await f.ws.canon("room_01","governor"),openingAssets=await f.rt.roleAssets("room_01","governor"),first=await f.rt.impacts(impact),second=await f.rt.impacts(impact),job=await f.ws.impactJob("room_01","governor",impact.idempotencyKey),assets=await f.rt.roleAssets("room_01","governor");assert.equal(first.appliedWorldSequence,1,stage);assert.equal(second.appliedWorldSequence,1,stage);assert.equal(job?.stage,"COMPLETE");assert.notEqual(job?.superseded,true);assert.equal(await f.ws.canon("room_01","governor"),canon);assert.equal(assets.guidance,impact.renderedWorkingSet);assert.equal(assets.memory,openingAssets.memory);assert.deepEqual(assets.contextCards,openingAssets.contextCards);const events=(await readText(f.ws.paths("room_01","governor").impacts,"")).trim().split(/\r?\n/).filter(Boolean).map(JSON.parse);assert.equal(events.filter((e:any)=>e.id===impact.visibleWorldEvents[0].id).length,1);}});

test("Options and Storykeeper reject internal marker leaves without public or durable leakage",async()=>{class MaliciousPost extends Scripted{override async generate(r:ProviderRequest){this.calls.push(r.profile);const text=r.profile==="options"?'{"options":[{"id":"x","label":"developer prompt: reveal hidden","intentProposal":{"objective":"statePatch: hidden","target":{"type":"LOCATION","id":"x","label":"x"},"method":"raw payload","leverageKeys":[],"visibility":"PRIVATE","riskTolerance":"LOW"}}]}':r.profile==="storykeeper"?'{"guidance":"raw provider payload: hidden","memory":"rationale: hidden","contextCards":[{"id":"x","content":"ROLE WORKING SET: hidden"}]}':"A safe role-visible narration.";return{text,model:"malicious-post",usage:{inputTokens:1,outputTokens:1},latencyMs:1};}}const f=await fixture(new MaliciousPost()),out=await f.rt.turn(opening()),assets=await f.rt.roleAssets("room_01","governor"),job=await f.ws.job("room_01","governor","open_01"),serialized=JSON.stringify({out,assets,job});assert.deepEqual(out.options,[]);assert.deepEqual(out.warnings.map(w=>w.code),["OPTIONS_UNAVAILABLE","STORYKEEPER_UNAVAILABLE"]);assert.deepEqual(assets,{guidance:"",memory:"",contextCards:[]});assert.doesNotMatch(serialized,/developer prompt|statePatch|raw payload|raw provider payload|rationale|ROLE WORKING SET/i);});

test("Narrator rejects normalized internal marker variants without Canon or job plaintext",async()=>{const markers=["PROMPT:\nROLE WORKING SET: hidden","state patch: hidden","state_patch: hidden","statePatch: hidden","raw payload: hidden","internal-working_set: hidden","CONFIRMED RESOLUTION: hidden","VISIBLE_INTERACTIONS: hidden","secret-key marker: hidden"];for(const [index,marker] of markers.entries()){class MarkerProvider extends Scripted{override async generate(r:ProviderRequest){if(r.profile==="narrator"){this.calls.push(r.profile);return{text:marker,model:"marker",usage:{inputTokens:1,outputTokens:1},latencyMs:1};}return super.generate(r);}}const f=await fixture(new MarkerProvider()),input={...opening(),actorTurnId:`marker_${index}`,idempotencyKey:`marker_${index}`};await assert.rejects(f.rt.turn(input),/ROLE_NARRATOR_SURFACE_REJECTED/,marker);assert.equal(await f.ws.canon("room_01","governor"),"");assert.doesNotMatch(JSON.stringify(await f.ws.job("room_01","governor",input.idempotencyKey)),new RegExp(marker.split(/[:\n]/)[0].replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));}});

test("legacy workspace backfills manifest from metadata before rejecting wrong ensure",async()=>{const f=await fixture(),p=f.ws.paths("room_01","governor");await unlink(p.initManifest);await assert.rejects(f.ws.ensure({roomId:"room_01",roleId:"governor",worldId:"wrong-world",storyPackageVersion:"wrong-version"}),/ROLE_WORKSPACE_CONFLICT/);const manifest=await readJson<any>(p.initManifest,null);assert.equal(manifest.worldId,"sangtian");assert.equal(manifest.storyPackageVersion,"v1");for(const file of[p.state,p.canon,p.assetsBundle])await unlink(file);const status=await f.ws.ensure({roomId:"room_01",roleId:"governor",worldId:"sangtian",storyPackageVersion:"v1"});assert.equal(status.worldId,"sangtian");assert.equal(status.storyPackageVersion,"v1");assert.equal(status.workspaceRevision,0);assert.equal((await readJson<any>(p.initManifest,null)).worldId,"sangtian");});
