/* Runtime copy of the frozen packages/shared continuous-openovel-v1 wire contract.
 * It intentionally has no package dependency because Batch B may not change package.json.
 */
export const OPENOVEL_ROLE_RUNTIME_MODE = "OPENOVEL_ROLE_V1" as const;
export const ROLE_NARRATIVE_INPUT_SCHEMA_VERSION = "role_narrative_input_v1" as const;
export const ROLE_NARRATIVE_OUTPUT_SCHEMA_VERSION = "role_narrative_output_v1" as const;
export const ROLE_RUNTIME_STATUS_SCHEMA_VERSION = "role_runtime_status_v1" as const;
export const ROLE_IMPACT_SYNC_SCHEMA_VERSION = "role_impact_sync_v1" as const;
export const MODEL_CALL_BUDGET_SCHEMA_VERSION = "model_call_budget_v1" as const;

export type RoleVisibleEventV1 = { schemaVersion:"role_visible_event_v1"; id:string; worldSequence:number; type:string; content:string; sourceRoleId?:string };
export type RoleVisibleInteractionV1 = { schemaVersion:"role_visible_interaction_v1"; id:string; sourceRoleId:string; requestKind:string; pressure:{objective:string;method:string;sourceRoleName:string;targetRoleName:string}; expiresAt?:string };
export type ModelCallBudgetV1 = { schemaVersion:typeof MODEL_CALL_BUDGET_SCHEMA_VERSION; kind:"NORMAL"|"AI_TARGET"|"CONVERGENCE"|"UNAFFECTED"; hardLimit:number; consumed:number };
export type RoleNarrativeInputV1 = { schemaVersion:typeof ROLE_NARRATIVE_INPUT_SCHEMA_VERSION; runtimeMode:typeof OPENOVEL_ROLE_RUNTIME_MODE; turnKind:"OPENING"|"RESULT"; roomId:string; roleId:string; actorTurnId:string; turnIndex:number; baseWorldSequence:number; appliedWorldSequence:number|null; contextSnapshotHash:string; renderedWorkingSet:string; readerAction?:string; confirmedResolution?:string; visibleWorldEvents:RoleVisibleEventV1[]; pendingInteractions:RoleVisibleInteractionV1[]; previousCanonHash?:string; modelCallBudget:ModelCallBudgetV1; idempotencyKey:string };
export type RoleImpactSyncV1 = { schemaVersion:typeof ROLE_IMPACT_SYNC_SCHEMA_VERSION; runtimeMode:typeof OPENOVEL_ROLE_RUNTIME_MODE; roomId:string; roleId:string; actorTurnId:string; baseWorldSequence:number; appliedWorldSequence:number; contextSnapshotHash:string; renderedWorkingSet:string; visibleWorldEvents:RoleVisibleEventV1[]; pendingInteractions:RoleVisibleInteractionV1[]; previousCanonHash?:string; idempotencyKey:string };
export type RoleNarrativeOptionV1 = { id:string; label:string; intentProposal?:{ objective:string; target:{type:"ROLE"|"PERSON"|"EVIDENCE"|"RESOURCE"|"LOCATION"|"INSTITUTION"|"PUBLIC_FRAME";id:string;label:string}; method:string; leverageKeys:string[]; visibility:"PRIVATE"|"LIMITED"|"OBSERVABLE"|"PUBLIC"; riskTolerance:"LOW"|"MEDIUM"|"HIGH"; effectClaim?:"REQUEST"|"CONTEST"|"TRANSFER"|"INJURY"|"PERMANENT_REMOVAL"|"OTHER" } };
export type RoleRuntimeUsageV1 = { narratorCalls:number;optionsCalls:number;storykeeperCalls:number;inputTokens:number;outputTokens:number };
export type RoleNarrativeWarningV1 = {code:string;severity:"LOW"|"MEDIUM"|"HIGH";blocksPlayer:false};
export type RoleNarrativeOutputV1 = { schemaVersion:typeof ROLE_NARRATIVE_OUTPUT_SCHEMA_VERSION;roomId:string;roleId:string;actorTurnId:string;narration:string;options:RoleNarrativeOptionV1[];canonHash:string;workspaceRevision:number;appliedWorldSequence:number;warnings:RoleNarrativeWarningV1[];usage:RoleRuntimeUsageV1 };
export type RoleRuntimeStatusV1 = {schemaVersion:typeof ROLE_RUNTIME_STATUS_SCHEMA_VERSION;runtimeMode:typeof OPENOVEL_ROLE_RUNTIME_MODE;roomId:string;roleId:string;worldId:string;storyPackageVersion:string;workspaceRevision:number;appliedWorldSequence:number;canonHash:string|null};

const exact=(v:Record<string,unknown>, keys:string[])=>Object.keys(v).every(k=>keys.includes(k));
const rec=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const str=(v:unknown)=>typeof v==="string"&&v.trim().length>0;
const nat=(v:unknown)=>Number.isInteger(v)&&Number(v)>=0;
const ids=(v:Record<string,unknown>)=>str(v.roomId)&&str(v.roleId)&&str(v.actorTurnId)&&str(v.contextSnapshotHash)&&str(v.renderedWorkingSet)&&str(v.idempotencyKey);
function events(v:unknown){return Array.isArray(v)&&v.every(e=>rec(e)&&exact(e,["schemaVersion","id","worldSequence","type","content","sourceRoleId"])&&e.schemaVersion==="role_visible_event_v1"&&str(e.id)&&nat(e.worldSequence)&&str(e.type)&&str(e.content)&&(e.sourceRoleId===undefined||str(e.sourceRoleId)));}
function interactions(v:unknown){return Array.isArray(v)&&v.every(i=>{if(!rec(i)||!exact(i,["schemaVersion","id","sourceRoleId","requestKind","pressure","expiresAt"])||!rec(i.pressure))return false;const pressure=i.pressure;return i.schemaVersion==="role_visible_interaction_v1"&&str(i.id)&&str(i.sourceRoleId)&&str(i.requestKind)&&exact(pressure,["objective","method","sourceRoleName","targetRoleName"])&&["objective","method","sourceRoleName","targetRoleName"].every(k=>str(pressure[k]))&&(i.expiresAt===undefined||str(i.expiresAt));});}
export function validateBudget(v:unknown):v is ModelCallBudgetV1{return rec(v)&&exact(v,["schemaVersion","kind","hardLimit","consumed"])&&v.schemaVersion===MODEL_CALL_BUDGET_SCHEMA_VERSION&&["NORMAL","AI_TARGET","CONVERGENCE","UNAFFECTED"].includes(String(v.kind))&&nat(v.hardLimit)&&nat(v.consumed)&&Number(v.consumed)<=Number(v.hardLimit);}
export function validateNarrativeInput(v:unknown):v is RoleNarrativeInputV1 {if(!rec(v)||!exact(v,["schemaVersion","runtimeMode","turnKind","roomId","roleId","actorTurnId","turnIndex","baseWorldSequence","appliedWorldSequence","contextSnapshotHash","renderedWorkingSet","readerAction","confirmedResolution","visibleWorldEvents","pendingInteractions","previousCanonHash","modelCallBudget","idempotencyKey"]))return false;const seqOk=v.turnKind==="OPENING"?v.appliedWorldSequence===null:nat(v.appliedWorldSequence)&&Number(v.appliedWorldSequence)>=1;return v.schemaVersion===ROLE_NARRATIVE_INPUT_SCHEMA_VERSION&&v.runtimeMode===OPENOVEL_ROLE_RUNTIME_MODE&&(v.turnKind==="OPENING"||v.turnKind==="RESULT")&&ids(v)&&nat(v.turnIndex)&&nat(v.baseWorldSequence)&&seqOk&&(v.readerAction===undefined||str(v.readerAction))&&(v.confirmedResolution===undefined||str(v.confirmedResolution))&&(v.previousCanonHash===undefined||str(v.previousCanonHash))&&events(v.visibleWorldEvents)&&interactions(v.pendingInteractions)&&validateBudget(v.modelCallBudget);}
export function validateImpact(v:unknown):v is RoleImpactSyncV1 {return rec(v)&&exact(v,["schemaVersion","runtimeMode","roomId","roleId","actorTurnId","baseWorldSequence","appliedWorldSequence","contextSnapshotHash","renderedWorkingSet","visibleWorldEvents","pendingInteractions","previousCanonHash","idempotencyKey"])&&v.schemaVersion===ROLE_IMPACT_SYNC_SCHEMA_VERSION&&v.runtimeMode===OPENOVEL_ROLE_RUNTIME_MODE&&ids(v)&&nat(v.baseWorldSequence)&&nat(v.appliedWorldSequence)&&(v.previousCanonHash===undefined||str(v.previousCanonHash))&&events(v.visibleWorldEvents)&&interactions(v.pendingInteractions);}
