import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{fileURLToPath}from"node:url";import{dirname,resolve}from"node:path";import{NUMERIC_EXPRESSION_OPERATORS as N,BOOLEAN_EXPRESSION_OPERATORS as B,DELAYED_EVENT_STATUSES as S,assertEndgamePackageV1,validateEndgamePackageV1,evaluateNumericExpression as en,evaluateBooleanExpression as eb,canonicalizeJcs,computeEndgamePackageHash,createEndgamePackageSnapshotV1}from"../src/endgame/endgame-package-v1.contract.mjs";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"../../.."),paths=["packages/templates/config/endgame/examples/sangtian.endgame.example.json","packages/templates/config/endgame/examples/caesar.endgame.example.json","packages/templates/config/endgame/fixtures/neutral-synthetic.endgame.fixture.json"],docs=await Promise.all(paths.map(async p=>JSON.parse(await readFile(resolve(root,p),"utf8")))),schema=JSON.parse(await readFile(resolve(root,"packages/shared/schemas/endgame/endgame-package-v1.schema.json"),"utf8")),hashManifest=JSON.parse(await readFile(resolve(root,"docs/auto-execute/evidence/generic-endgame-v3-s0/package-hashes.json"),"utf8")),cp=x=>structuredClone(x),bad=(mut,re)=>{const x=cp(docs[0]);mut(x);const r=validateEndgamePackageV1(x);assert.equal(r.ok,false);assert.match(r.issues.join(" "),re)};
for(const[i,p]of paths.entries())test(`valid package ${p}`,()=>assert.equal(assertEndgamePackageV1(docs[i]),docs[i]));
test("schema uses Draft 2020-12",()=>assert.equal(schema.$schema,"https://json-schema.org/draft/2020-12/schema"));
test("schema forbids embedded packageHash",()=>{assert.equal(schema.additionalProperties,false);assert.equal(Object.hasOwn(schema.properties,"packageHash"),false)});
test("schema numeric allowlist equals executable allowlist",()=>assert.deepEqual(schema.$defs.numericExpression.oneOf.map(x=>x.required[0]),N));
test("schema boolean allowlist equals state constant plus executable allowlist",()=>assert.deepEqual(schema.$defs.booleanExpression.oneOf.map(x=>x.required[0]),["state","constant",...B]));
test("schema delayed statuses equal executable statuses",()=>assert.deepEqual(schema.$defs.factSelector.properties.statuses.items.enum,S));
test("schema narrative contract has no implicit top-level defaults",()=>assert.deepEqual(new Set(schema.$defs.narrative.required),new Set(["language","pointOfView","tone","pacing","length","paragraphPlan","worldImagery","forbiddenPhrases","scopeConstraints","fallback"])));
test("committed hash manifest matches RFC 8785 hashes",()=>{for(const [index,row]of hashManifest.packages.entries()){assert.equal(row.path,paths[index]);assert.equal(row.packageHash,computeEndgamePackageHash(docs[index]))}});
test("numeric allowlist",()=>assert.deepEqual(N,["metric","state","constant","add","subtract","multiply","divide","average","min","max","invert","clamp","tagCount","factCount"]));test("boolean allowlist",()=>assert.deepEqual(B,["all","any","not","gt","gte","lt","lte","eq","neq","in","factExists","axisOutcomeIs"]));test("delayed statuses",()=>assert.deepEqual(S,["PENDING","OCCURRED","RESOLVED","CANCELLED","EXPIRED"]));test("TRIGGERED absent",()=>assert.equal(JSON.stringify(docs).includes("TRIGGERED"),false));test("neutral is world-neutral",()=>assert.doesNotMatch(JSON.stringify(docs[2]),/sangtian|zhejiang|governor|caesar|senate|imperial|reform|grain/iu));
const c={metrics:{a:10,b:4},state:{n:3,s:"READY",ok:true},facts:[{sourceType:"PLAYER_ACTION",category:"ACHIEVEMENT",status:"OCCURRED",polarity:"POSITIVE",visibility:"PLAYER",tags:["x"],magnitude:2}],axisOutcomes:{world:"good"}};
const numeric=[[{metric:"a"},10],[{state:"n"},3],[{constant:7},7],[{add:[{constant:2},{constant:3}]},5],[{subtract:[{constant:7},{constant:2}]},5],[{multiply:[{constant:3},{constant:4}]},12],[{divide:[{constant:8},{constant:2}]},4],[{average:[{constant:2},{constant:4}]},3],[{min:[{constant:2},{constant:4}]},2],[{max:[{constant:2},{constant:4}]},4],[{invert:{value:{constant:25},min:{constant:0},max:{constant:100}}},75],[{clamp:{value:{constant:120},min:{constant:0},max:{constant:100}}},100],[{tagCount:{selector:{sourceTypes:["PLAYER_ACTION"]},tag:"x"}},1],[{factCount:{categories:["ACHIEVEMENT"]}},1]];for(const[x,v]of numeric)test(`numeric ${Object.keys(x)[0]}`,()=>assert.equal(en(x,c),v));
const boolean=[[{all:[{constant:true},{not:{constant:false}}]},true],[{any:[{constant:false},{constant:true}]},true],[{not:{constant:false}},true],[{gt:[{constant:2},{constant:1}]},true],[{gte:[{constant:2},{constant:2}]},true],[{lt:[{constant:1},{constant:2}]},true],[{lte:[{constant:2},{constant:2}]},true],[{eq:[{state:"s"},{constant:"READY"}]},true],[{neq:[{constant:1},{constant:2}]},true],[{in:[{state:"s"},{constant:["READY","DONE"]}]},true],[{factExists:{statuses:["OCCURRED"]}},true],[{axisOutcomeIs:["world","good"]},true]];for(const[x,v]of boolean)test(`boolean ${Object.keys(x)[0]}`,()=>assert.equal(eb(x,c),v));
test("divide zero fails",()=>assert.throws(()=>en({divide:[{constant:1},{constant:0}]},c),/DIVIDE_BY_ZERO/));test("non finite input fails",()=>assert.throws(()=>canonicalizeJcs({x:Infinity}),/NON_FINITE/));test("invalid clamp fails",()=>assert.throws(()=>en({clamp:{value:{constant:2},min:{constant:3},max:{constant:1}}},c),/INVALID_BOUNDARY/));test("JCS sorts keys",()=>assert.equal(canonicalizeJcs({z:1,a:2}),'{"a":2,"z":1}'));test("JCS insertion independent",()=>assert.equal(canonicalizeJcs({b:1,a:2}),canonicalizeJcs({a:2,b:1})));test("JCS negative zero",()=>assert.equal(canonicalizeJcs({x:-0}),'{"x":0}'));test("JCS cycle fails",()=>{const x={};x.x=x;assert.throws(()=>canonicalizeJcs(x),/CYCLE/)});test("hash stable",()=>assert.equal(computeEndgamePackageHash(docs[0]),computeEndgamePackageHash(JSON.parse(canonicalizeJcs(docs[0])))));test("hash changes",()=>{const x=cp(docs[0]);x.policyVersion="1.0.1";assert.notEqual(computeEndgamePackageHash(x),computeEndgamePackageHash(docs[0]))});test("snapshot freezes ref",()=>{const x=createEndgamePackageSnapshotV1(docs[1]);assert.equal(x.policyId,docs[1].policyId);assert.match(x.packageHash,/^[0-9a-f]{64}$/)});
test("snapshot recursively freezes package document",()=>{const x=createEndgamePackageSnapshotV1(docs[1]);assert.equal(Object.isFrozen(x.packageDocument),true);assert.equal(Object.isFrozen(x.packageDocument.metrics),true);assert.equal(Object.isFrozen(x.packageDocument.metrics[0]),true);assert.throws(()=>{x.packageDocument.metrics[0].label="changed"},/read only|Cannot assign/)});
test("expression evaluator enforces global node limit",()=>assert.throws(()=>eb({all:Array.from({length:501},()=>({constant:true}))},c),/EXPRESSION_LIMIT/));
test("expression evaluator enforces recursive depth limit",()=>{let x={constant:true};for(let i=0;i<21;i++)x={not:x};assert.throws(()=>eb(x,c),/EXPRESSION_LIMIT/)});
const negatives=[
 [x=>x.packageHash="x",/packageHash/],[x=>x.extra=1,/unknown key/],[x=>x.policyVersion="v1",/SemVer/],[x=>x.metrics[1].metricId=x.metrics[0].metricId,/duplicate metric/],[x=>x.metrics[0].initialValue=999,/range invalid/],[x=>x.derivedMetrics=[{derivedMetricId:"a",expression:{metric:"b"}},{derivedMetricId:"b",expression:{metric:"a"}}],/cycle/],[x=>x.completion.when={mystery:[]},/unknown boolean operator/],[x=>x.completion.when={gte:[{mystery:1},{constant:1}]},/unknown numeric operator/],[x=>x.completion.when={gte:[{metric:"missing"},{constant:1}]},/unknown metric/],[x=>x.completion.when={eq:[{state:"missing"},{constant:1}]},/unknown state/],[x=>x.outcomeAxes[0].outcomes.forEach(o=>delete o.fallback),/fallback/],[x=>x.outcomeAxes[0].outcomes.forEach(o=>o.fallback=true),/fallback/],[x=>x.outcomeAxes[0].outcomes[0].outcomeId="fallback",/duplicate outcome/],[x=>x.presentation.axisOrder=["missing"],/unknown axis/],[x=>x.presentation.metricOrder=["missing"],/unknown metric/],[x=>x.presentation.sections[0].slotIds=["missing"],/unknown slot/],[x=>x.detailCompilation.slots[0].scoringProfileId="missing",/unknown scoring/],[x=>{x.detailCompilation.slots[3].fallback="USE_TEMPLATE";delete x.detailCompilation.slots[3].fallbackTemplate},/fallbackTemplate/],[x=>x.detailCompilation.slots[0].selector.statuses=["TRIGGERED"],/invalid status/],[x=>x.detailCompilation.sceneArchetypes.forEach(s=>s.fallback=true),/fallback/],[x=>x.narrative.scopeConstraints.PART.allowLifetimeClosure=true,/PART boundary/],[x=>x.narrative.scopeConstraints.PART.requireUnresolvedHook=false,/PART boundary/],[x=>x.narrative.length.targetChars=9999,/min <= target/],[x=>x.narrative.paragraphPlan[0].requiredSlots=["missing"],/unknown slot/],[x=>x.narrative.paragraphPlan[0].requiredAxes=["missing"],/unknown axis/],[x=>x.narrative.worldImagery.requiredTags=["missing"],/unknown tag/],[x=>x.completion.when={all:[]},/requires 1/],[x=>x.completion.when={gte:[{constant:1}]},/requires 2/],[x=>x.completion.when={gte:[{divide:[{constant:1},{constant:0}]},{constant:1}]},/division by zero/],[x=>x.completion.when={eq:[{eval:"x"},{constant:1}]},/unknown numeric operator|forbidden key/],
[x=>x.derivedMetrics=[{derivedMetricId:"self",expression:{metric:"self"}}],/cycle/],
[x=>x.detailCompilation.styleProfiles[0].when={gte:[{tagCount:{selector:{},tag:"not-registered"}},{constant:1}]},/unknown tag/],
[x=>x.combinationOverrides[0].when={axisOutcomeIs:["world_outcome"]},/axisOutcomeIs requires/],
[x=>x.completion.when={eq:[{constant:[1,2]},{constant:1}]},/JSON scalar/],
[x=>x.narrative.fallback.allowedPlaceholders.push("missing.0.text"),/unknown slot/],
[x=>x.narrative.fallback.paragraphTemplates.PART[0]="{{not_allowed}}",/not allowed/],
[x=>{let y={constant:true};for(let i=0;i<21;i++)y={not:y};x.completion.when=y},/depth limit/],
[x=>x.completion.when={all:Array.from({length:501},()=>({constant:true}))},/node limit/]
];for(const[i,v]of negatives.entries())test(`negative ${i+1}`,()=>bad(v[0],v[1]));
