export const CHAPTER_ORCHESTRATOR_ERROR_CODES = {
  STATE_MISSING: "CHAPTER_ORCHESTRATOR_STATE_MISSING",
  STATE_CORRUPT: "CHAPTER_ORCHESTRATOR_STATE_CORRUPT",
  ROUTE_MISMATCH: "CHAPTER_ORCHESTRATOR_ROUTE_MISMATCH",
  CONTENT_INVALID: "CHAPTER_ORCHESTRATOR_CONTENT_INVALID",
  OPTIONAL_UNDEFINED: "CHAPTER_ORCHESTRATOR_OPTIONAL_UNDEFINED",
  DECISION_MISMATCH: "CHAPTER_ORCHESTRATOR_DECISION_MISMATCH",
  SEAT_NOT_REQUIRED: "CHAPTER_ORCHESTRATOR_SEAT_NOT_REQUIRED",
  ACTION_BUDGET_EXCEEDED: "CHAPTER_ORCHESTRATOR_ACTION_BUDGET_EXCEEDED",
  ACTION_EXPIRED: "CHAPTER_ORCHESTRATOR_ACTION_EXPIRED",
  DEADLINE_FAIL_CLOSED: "CHAPTER_ORCHESTRATOR_DEADLINE_FAIL_CLOSED",
  DEFAULT_NOT_ALLOWED: "CHAPTER_ORCHESTRATOR_DEFAULT_NOT_ALLOWED",
  STALE_ACTION: "CHAPTER_ORCHESTRATOR_STALE_ACTION",
  KERNEL_EXHAUSTED_EARLY: "CHAPTER_ORCHESTRATOR_KERNEL_EXHAUSTED_EARLY",
  CLOSE_POLICY_NOT_MET: "CHAPTER_ORCHESTRATOR_CLOSE_POLICY_NOT_MET",
  SETTLEMENT_MISMATCH: "CHAPTER_ORCHESTRATOR_SETTLEMENT_MISMATCH",
  CAS_CONFLICT: "CHAPTER_ORCHESTRATOR_CAS_CONFLICT",
  INVALID_PHASE: "CHAPTER_ORCHESTRATOR_INVALID_PHASE",
  N8_FORBIDDEN: "CHAPTER_ORCHESTRATOR_N8_FORBIDDEN",
} as const;

export type ChapterOrchestratorErrorCode =
  (typeof CHAPTER_ORCHESTRATOR_ERROR_CODES)[keyof typeof CHAPTER_ORCHESTRATOR_ERROR_CODES];

export class ChapterOrchestratorError extends Error {
  constructor(
    readonly code: ChapterOrchestratorErrorCode,
    readonly detail?: string,
  ) {
    super(detail ? `${code}:${detail}` : code);
    this.name = "ChapterOrchestratorError";
  }
}

export function failChapterOrchestrator(
  code: ChapterOrchestratorErrorCode,
  detail?: string,
): never {
  throw new ChapterOrchestratorError(code, detail);
}
