import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync, cpSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { assertPressureSpinePackage, assertPressureSpineSchemaProfile, buildPressureSpineRuntimeIndex, loadPressureSpinePackage, readPressureSpineDirectory, sha256Bytes, validatePressureSpinePackage, type PressureSpineFileMap } from "../src/pressure-spine/index";

const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const configRoot=resolve(packageRoot,"config/sangtian"),artifactRoot=resolve(configRoot,"pressure-spine-v1.0"),contentRoot=resolve(artifactRoot,"source"),registryPath=resolve(configRoot,"strategy-registry.json"),importer=resolve(packageRoot,"scripts/import-sangtian-pressure-spine.mjs"),archive=resolve(artifactRoot,"source-package/sangtian_complete_story_content_package_v1_1.zip");
const expectedZip="38AC19ABFBB89288F80C5E128141B705535D2A9E11D370B293402DC106760317",expectedT0="04D5E8D4533D86890A79058C25252D33E001668921A2BBD8FFDE401CDD2B6238";
const legacy={sangtian_v1_1:"E4047A888450E589A0E3AD2C9F702218BAAE54737C713A217ABAAF3CAC17D8BD",sangtian_v1_2:"D21757ACD32D29BE647E9A3796E85886138A3C7AEACAD1541CEDE947198242B2"};
const accepted=()=>readPressureSpineDirectory(contentRoot);
const bytes=(v:unknown)=>new TextEncoder().encode(`${JSON.stringify(v,null,2)}\n`);
function clone(files:PressureSpineFileMap){return new Map([...files].map(([p,b])=>[p,new Uint8Array(b)]));}
function mutateJson(files:PressureSpineFileMap,path:string,fn:(v:any)=>void){const out=clone(files),v=JSON.parse(new TextDecoder().decode(out.get(path)!));fn(v);out.set(path,bytes(v));return out;}
function codes(files:PressureSpineFileMap){return validatePressureSpinePackage(files,{expectedSourceSha256:expectedT0,expectedSourceLineCount:30547,expectedNodeIds:["P0","N1","N2","N3","N4","N5","N6","N7"],expectedSeatCount:6,validateInventory:false,requireNativeAuditPass:true}).issues.map(x=>x.code);}
function expectCode(files:PressureSpineFileMap,code:string){assert.ok(codes(files).includes(code),`${code} absent: ${codes(files).join(",")}`);}
function addInventory(files:PressureSpineFileMap){
  const paths=[...files.keys(),"inventory.json"].sort();let inv:any={schemaVersion:"neutral_inventory_v1",files:paths.map(path=>({path,byteSize:path==="inventory.json"?0:files.get(path)!.byteLength,sha256:path==="inventory.json"?"0".repeat(64):sha256Bytes(files.get(path)!)}))};
  for(let i=0;i<10;i++){const self=inv.files.find((x:any)=>x.path==="inventory.json");self.sha256="0".repeat(64);let b=bytes(inv);self.byteSize=b.byteLength;self.sha256=sha256Bytes(bytes(inv));b=bytes(inv);if(b.byteLength===self.byteSize){files.set("inventory.json",b);return files;}self.byteSize=b.byteLength;}
  throw new Error("inventory did not converge");
}
function neutralPackage():PressureSpineFileMap{
  const f=new Map<string,Uint8Array>(),source="A".repeat(64),seats=[{seatId:"seat.alpha",roleKey:"alpha"},{seatId:"seat.beta",roleKey:"beta"}],actors=[{actorId:"actor.alpha",seatId:"seat.alpha",activeFrom:"P0",activeUntil:"N1"},{actorId:"actor.beta",seatId:"seat.beta",activeFrom:"P0",activeUntil:"N1"}],all=seats.map(x=>x.seatId),obj="obj.token";
  f.set("global/seats.json",bytes({seats}));f.set("global/actors.json",bytes({actors}));f.set("global/objects.json",bytes({objects:[{objectId:obj}]}));f.set("global/knowledge-and-handoffs.json",bytes({handoffs:[]}));f.set("validation/source-index-reference-map.json",bytes({paragraphs:{}}));f.set("validation/source-ref-audit.json",bytes({verdict:"PASS",sourceSha256:source}));f.set("validation/unresolved-unknowns.json",bytes({verdict:"PASS",items:[]}));f.set("finale/ending-rules.json",bytes({sourceSha256:source,inputRule:"frozen inputs only",worldTracks:["track.neutral"],seatVerdicts:seats.map(x=>({seatId:x.seatId}))}));
  const scene=(sceneId:string,nodeId:string,type:string,pred:string[],succ:string[])=>({sceneId,nodeId,sceneType:type,visibility:"PUBLIC",knownBy:all,sourceClaimIds:[`claim.${nodeId}`],applicableObjectIds:[obj],predecessorIds:pred,successorIds:succ});
  for(const [seq,nodeId] of ["P0","N1"].entries()){
    const claimId=`claim.${nodeId}`,adaptId=`adapt.${nodeId}`;f.set(`nodes/${nodeId}/node.json`,bytes({nodeId,sequence:seq,nextNodeId:nodeId==="P0"?"N1":null,sourceSha256:source,contestedObjectIds:[obj],secondaryObjectIds:[],actionBudget:{preparePerSeat:nodeId==="P0"?0:1,commitPerSeat:nodeId==="P0"?0:1,reactionPerSeat:0}}));f.set(`nodes/${nodeId}/source-evidence.jsonl`,new TextEncoder().encode(`${JSON.stringify({claimId,nodeId,provenanceClass:"ADAPTATION_RULE",adaptationDecisionId:adaptId,visibility:"PUBLIC",knownBy:all,applicableObjectIds:[obj]})}\n`));f.set(`nodes/${nodeId}/adaptations.json`,bytes({adaptations:[{adaptationDecisionId:adaptId,reviewStatus:"APPROVED",rationale:"neutral",invariantsToPreserve:["determinism"]}]}));
    const scenes=nodeId==="P0"?[scene("scene.p0.open","P0","OPENING",[],["scene.n1.open"])]:[scene("scene.n1.open","N1","OPENING",["scene.p0.open"],["scene.n1.prepare"]),scene("scene.n1.prepare","N1","AFTER_PREPARE",["scene.n1.open"],["scene.n1.commit"]),scene("scene.n1.commit","N1","COMMIT_CONFRONTATION",["scene.n1.prepare"],["scene.n1.high","scene.n1.mid","scene.n1.low"]),...(["high","mid","low"] as const).flatMap(level=>[scene(`scene.n1.${level}`,"N1","SETTLEMENT_RESULT",["scene.n1.commit"],[`scene.n1.transition.${level}`]),scene(`scene.n1.transition.${level}`,"N1","TRANSITION",[`scene.n1.${level}`],["finale.opening"])])];
    f.set(`nodes/${nodeId}/scene-flow.json`,bytes({nodeId,decisionBeats:[{beatId:`beat.${nodeId}`}],scenes,inputRealizations:[{inputId:`input.${nodeId}`}]}));
    f.set(`nodes/${nodeId}/seat-content.json`,bytes({seats:seats.map((s,i)=>{const fr=`known.${nodeId}.${i}`;return{seatContentId:`seatcontent.${nodeId}.${i}`,seatId:s.seatId,currentActorId:actors[i].actorId,knownFacts:[{factRefId:fr,sourceKind:"CLAIM",claimId,currentActorId:actors[i].actorId,knownBy:[s.seatId]}],knownFactIds:[fr],unknownFacts:[],unknownFactIds:[],dialogueSeeds:[{dialogueSeedId:`dialogue.${nodeId}.${i}`,knownBy:[s.seatId]}]};})}));
    f.set(`nodes/${nodeId}/npc-defaults.json`,bytes({seatDefaults:seats.map((s,i)=>({defaultPolicyId:`default.${nodeId}.${i}`,seatId:s.seatId,currentActorId:actors[i].actorId})),inputFallbackPolicies:[{fallbackId:`fallback.${nodeId}`}]}));
    if(nodeId==="P0")f.set(`nodes/${nodeId}/settlement.json`,bytes({branches:[{branchId:"branch.p0",frozenResultId:"frozen.p0",frozenFactIds:["frozen.p0.fact"],frozenFactsById:[{frozenFactId:"frozen.p0.fact"}],objectOutcomes:[{objectId:obj,versionId:`${obj}@P0.LOCKED.v1`,availableFrom:"frozen.p0",custodyMode:"FIXED",custodyRule:"stable",knownBy:all}]}]}));
    else f.set(`nodes/${nodeId}/settlement.json`,bytes({balanceSeedStatus:"UNVALIDATED_BALANCE_SEED",branchSelector:{evaluationOrder:["HIGH","MID","LOW"],selectors:{HIGH:{key:"score",op:">=",value:2},MID:{key:"score",op:">=",value:1},LOW:{otherwise:true}}},defaultTrajectory:{defaultInputState:{score:0},defaultBranchId:"branch.n1.low"},branches:["HIGH","MID","LOW"].map(level=>({level,branchId:`branch.n1.${level.toLowerCase()}`,frozenResultId:`frozen.n1.${level}`,frozenFactIds:[`frozen.n1.${level}.fact`],frozenFactsById:[{frozenFactId:`frozen.n1.${level}.fact`}],objectOutcomes:[{objectId:obj,versionId:`${obj}@N1.${level}.v1`,availableFrom:`frozen.n1.${level}`,custodyMode:"DETERMINISTIC",custodyRule:"stable",knownBy:all}]}))}));
  }
  f.set("manifest.json",bytes({schemaVersion:"neutral_content_manifest_v1",packageId:"neutral",packageVersion:"1",sourceSha256:source,sourceLineCount:1,nodes:["P0","N1"],seatIds:all,files:[]}));
  const manifest=JSON.parse(new TextDecoder().decode(f.get("manifest.json")!));manifest.files=[...f.keys(),"inventory.json"].sort();f.set("manifest.json",bytes(manifest));return addInventory(f);
}

function runtimeArgs(){const loader=process.env.PRESSURE_SPINE_TEST_LOADER;return loader?["--experimental-transform-types","--experimental-loader",loader]:["--import","tsx"];}
function runImporter(out:string,reg:string){const args=[...runtimeArgs(),importer,"--input-dir",contentRoot,"--source-package-zip",archive,"--output-root",out,"--registry-path",reg];const t0=process.env.SANGTIAN_T0_PATH;if(t0)args.push("--t0",t0);const r=spawnSync(process.execPath,args,{encoding:"utf8",env:process.env});assert.equal(r.status,0,`${r.stdout}\n${r.stderr}`);return JSON.parse(r.stdout);}

test("IMP-002 immutable accepted archive identity",()=>{const b=readFileSync(archive);assert.equal(b.byteLength,277041);assert.equal(sha256Bytes(b),expectedZip);});
test("IMP-003 accepted package and native validator-compatible contracts pass",()=>{const report=assertPressureSpinePackage(accepted(),{expectedSourceSha256:expectedT0,expectedSourceLineCount:30547,expectedNodeIds:["P0","N1","N2","N3","N4","N5","N6","N7"],expectedSeatCount:6,sourceText:process.env.SANGTIAN_T0_PATH?readFileSync(process.env.SANGTIAN_T0_PATH,"utf8"):undefined});assert.equal(report.counts.fileCount,95);assert.equal(report.counts.sceneCount,145);});
test("neutral synthetic fixture passes generic validation and indexing without story vocabulary",()=>{const f=neutralPackage();const text=[...f.values()].map(b=>new TextDecoder().decode(b)).join("\n");for(const term of ["桑田","毁堤","账册","沈一石"])assert.equal(text.includes(term),false);assert.equal(validatePressureSpinePackage(f,{validateInventory:true,requireNativeAuditPass:true}).verdict,"PASS");const index=buildPressureSpineRuntimeIndex({files:f,worldId:"neutral",runtimeProfile:"PRESSURE_SPINE_NEUTRAL_TEST_V1",registeredPackageVersion:"neutral_v1",sourcePackageSha256:"C".repeat(64),sourcePackageByteSize:1,sourcePackageArchivePath:"source-package/neutral.zip",expectedSourceSha256:"A".repeat(64),expectedSourceLineCount:1,legacyStrategyLocks:{}});assert.deepEqual(index.nodeIds,["P0","N1"]);assert.deepEqual(index.seatIds,["seat.alpha","seat.beta"]);assert.equal(index.runtimeProfile,"PRESSURE_SPINE_NEUTRAL_TEST_V1");});
test("IMP-004 duplicate stable ID rejected",()=>expectCode(mutateJson(accepted(),"nodes/N1/scene-flow.json",v=>v.scenes[1].sceneId=v.scenes[0].sceneId),"CONTENT_STABLE_ID_DUPLICATE"));
test("IMP-005 bad source reference rejected",()=>{const f=clone(accepted()),p="nodes/P0/source-evidence.jsonl",rows=new TextDecoder().decode(f.get(p)!).trim().split(/\r?\n/).map(JSON.parse);const c=rows.find((x:any)=>x.provenanceClass==="SOURCE_FACT");c.sourceRefs[0].lineEnd=999999;f.set(p,new TextEncoder().encode(rows.map(JSON.stringify).join("\n")+"\n"));expectCode(f,"CONTENT_SOURCE_REF_INVALID");});
test("IMP-006 asymmetric graph rejected",()=>expectCode(mutateJson(accepted(),"nodes/N2/scene-flow.json",v=>v.scenes[0].successorIds=v.scenes[0].successorIds.slice(1)),"CONTENT_GRAPH_EDGE_ASYMMETRIC"));
test("IMP-007 unauthorized knowledge rejected",()=>expectCode(mutateJson(accepted(),"nodes/N6/scene-flow.json",v=>v.scenes.find((x:any)=>x.sceneId==="scene.n6.opening.public").sourceClaimIds.push("N6-SF-04")),"CONTENT_KNOWLEDGE_UNAUTHORIZED"));
test("IMP-008 bad object version rejected",()=>expectCode(mutateJson(accepted(),"nodes/N3/settlement.json",v=>v.branches[0].objectOutcomes[0].versionId="obj.wrong@N3.HIGH.v1"),"CONTENT_OBJECT_VERSION_INVALID"));
test("bad source hash rejected",()=>expectCode(mutateJson(accepted(),"manifest.json",v=>v.sourceSha256="B".repeat(64)),"CONTENT_SOURCE_SHA_MISMATCH"));
test("bad opening projection rejected",()=>expectCode(mutateJson(accepted(),"nodes/N7/scene-flow.json",v=>v.scenes[0].openingProjectionVariants[0].requiredObjectVersionIds.push("obj.missing@N6.HIGH.v1")),"CONTENT_OPENING_PROJECTION_INVALID"));
test("IMP-009 exact institutional seats",()=>{const i=JSON.parse(readFileSync(resolve(artifactRoot,"runtime-index.json"),"utf8"));assert.deepEqual(i.seatIds,["seat.zhejiang_governor","seat.zhejiang_administration","seat.qingliu_law","seat.jiangnan_merchant","seat.sili_weaving","seat.cabinet_finance"]);});
test("IMP-010 legacy hashes/default unchanged and pressure version loads",()=>{for(const [v,h] of Object.entries(legacy)){const p=resolve(configRoot,v==="sangtian_v1_1"?"continuous-strategy-v1.1/manifest.json":"continuous-strategy-v1.2/manifest.json");assert.equal(sha256Bytes(readFileSync(p)),h);}const registry=JSON.parse(readFileSync(registryPath,"utf8"));assert.equal(registry.defaultStrategyVersion,"sangtian_v1_2");assert.deepEqual(Object.keys(registry.strategies),["sangtian_v1_1","sangtian_v1_2","sangtian_pressure_v1_0"]);assert.equal(loadPressureSpinePackage(registryPath,"sangtian_pressure_v1_0").runtimeIndex.sceneIds.length,145);});
test("IMP-011 two imports are byte-identical",()=>{const root=mkdtempSync(resolve(tmpdir(),"pressure-import-"));try{const outs=[];for(const n of [1,2]){const dir=resolve(root,`r${n}`),out=resolve(dir,"pressure-spine-v1.0"),reg=resolve(dir,"strategy-registry.json");mkdirSync(dir,{recursive:true});writeFileSync(reg,readFileSync(registryPath));runImporter(out,reg);outs.push({out,reg});}for(const p of ["manifest.json","runtime-index.json","manifest.lock.json","source-package/sangtian_complete_story_content_package_v1_1.zip"])assert.equal(sha256Bytes(readFileSync(resolve(outs[0].out,p))),sha256Bytes(readFileSync(resolve(outs[1].out,p))));assert.equal(sha256Bytes(readFileSync(outs[0].reg)),sha256Bytes(readFileSync(outs[1].reg)));}finally{rmSync(root,{recursive:true,force:true});}});
test("IMP-012 UNKNOWN claims are never Frozen facts",()=>{const unknown=new Set<string>();for(const n of ["P0","N1","N2","N3","N4","N5","N6","N7"]){for(const line of readFileSync(resolve(contentRoot,`nodes/${n}/source-evidence.jsonl`),"utf8").split(/\r?\n/).filter(Boolean)){const c=JSON.parse(line);if(c.provenanceClass==="UNKNOWN")unknown.add(c.claimId);}const s=JSON.parse(readFileSync(resolve(contentRoot,`nodes/${n}/settlement.json`),"utf8"));for(const b of s.branches)for(const id of b.frozenFactIds)assert.equal(unknown.has(id),false);}});
test("IMP-013 eighteen predecessor projections indexed",()=>{const i=JSON.parse(readFileSync(resolve(artifactRoot,"runtime-index.json"),"utf8"));assert.equal(i.openingProjectionIds.length,18);});
test("IMP-014 legacy schema cannot masquerade as pressure content",()=>{const f=new Map<string,Uint8Array>();f.set("manifest.json",readFileSync(resolve(configRoot,"continuous-strategy-v1.2/manifest.json")));assert.throws(()=>assertPressureSpineSchemaProfile(f),(e:any)=>e.code==="CONTENT_SCHEMA_PROFILE_MISMATCH");});
