import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";
import { sangtianRuntimeFixture } from "../src/runtime-contract/fixtures";
import { DeterministicSettlementEngine, InMemorySettlementCoordinator, validateNarrativeDisposition, validatePlayerActionIntent, validateProtectedNarrativeBlock, validateSettlementPackage } from "../src/runtime-contract/settlement";
import type { PlayerActionIntent, SettlementPackage, SettlementSnapshot, WorldRuntimeContract } from "../src/runtime-contract/types";

const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const snapshot = (contract: WorldRuntimeContract): SettlementSnapshot => ({ state: clone(contract.openingState), events: [], pending: [] });
const intent = (contract: WorldRuntimeContract, rawText = "free form"): PlayerActionIntent => ({ actionId: `${contract.worldId}.action.one`, runId: `${contract.worldId}.run.one`, actorId: contract.roles[0].actorId, rawText, submittedAt: "2026-08-03T00:00:00.000Z", expectedStateRevision: 0, intentType: "USE_CAPABILITY", referencedEntityIds: [contract.entities[2].id], proposedCapabilityId: contract.capabilities[0].id, explicitCommitment: false, explicitOrder: false, confidence: 1 });
const config = (contract: WorldRuntimeContract, protectedRender = true): SettlementPackage => { const rule = contract.causalRules[0]; const actors = contract.roles.map((role) => role.actorId); return { bindings: [{ id: `${contract.worldId}.binding.primary`, intentType: "USE_CAPABILITY", capabilityId: rule.capabilityId, immediateRuleIds: [rule.id], delayedRuleIds: [], echoRoutes: [
  { category: "PERSONAL", ruleId: rule.id, effectIndex: 0, audience: { kind: "ORIGIN_ACTOR" }, summary: "The chosen action takes effect." },
  { category: "CROSS_PLAYER", ruleId: rule.id, effectIndex: Math.min(1, rule.effects.length - 1), audience: { kind: "OTHER_PLAYERS" }, summary: "Another participant reacts within their authority." },
  { category: "WORLD", ruleId: rule.id, effectIndex: 2, audience: { kind: "VISIBILITY_ACTORS" }, summary: "The shared situation gains pressure." },
], renderPolicy: protectedRender ? "PROTECTED_TEMPLATE" : "MODEL_ALLOWED", ...(protectedRender ? { protectedTemplate: "Settled: {summary}" } : {}) }], fallback: { locale: contract.styleProfile.locale, playerOutcomePrefix: "Outcome:", reactionPrefix: "Reaction:", worldPressurePrefix: "Pressure:", nextDecisionPoint: "Choose whether to continue or change course." } }; };

test("the generic engine settles a typed package with all three causal echoes", () => { const engine = new DeterministicSettlementEngine(); const contract = sangtianRuntimeFixture; const result = engine.settle(contract, config(contract), snapshot(contract), intent(contract)); assert.equal(result.kind, "ACCEPTED"); if (result.kind !== "ACCEPTED") return; assert.ok(result.result.envelope.personalEffects.length); assert.ok(result.result.envelope.crossPlayerEffects.length); assert.ok(result.result.envelope.worldEffects.length); assert.equal(new Set(result.result.events.map((event) => event.eventId)).size, result.result.events.length); assert.equal(result.result.snapshot.state.revision, 1); });

test("intent validator is exact and validates all required fields", () => { const valid = intent(sangtianRuntimeFixture); assert.deepEqual(validatePlayerActionIntent(valid, sangtianRuntimeFixture), valid); for (const field of Object.keys(valid)) { if (field === "proposedCapabilityId") continue; const broken = clone(valid) as unknown as Record<string, unknown>; delete broken[field]; assert.throws(() => validatePlayerActionIntent(broken, sangtianRuntimeFixture), /MISSING|INVALID|REQUIRED/); } assert.throws(() => validatePlayerActionIntent({ ...valid, extra: true }, sangtianRuntimeFixture), /UNKNOWN_FIELD/); });
test("intent rejects dangling duplicate unauthorized and malformed values", () => { const valid = intent(sangtianRuntimeFixture); assert.throws(() => validatePlayerActionIntent({ ...valid, actorId: sangtianRuntimeFixture.roles[1].actorId }, sangtianRuntimeFixture), /ACTOR_CAPABILITY/); assert.throws(() => validatePlayerActionIntent({ ...valid, referencedEntityIds: [valid.referencedEntityIds[0], valid.referencedEntityIds[0]] }, sangtianRuntimeFixture), /DUPLICATE/); for (const patch of [{ submittedAt: "today" }, { expectedStateRevision: -1 }, { confidence: 2 }, { referencedEntityIds: ["ghost.entity"] }]) assert.throws(() => validatePlayerActionIntent({ ...valid, ...patch }, sangtianRuntimeFixture)); });
test("intent types cannot be upgraded by flags or low-confidence proposal", () => { const valid = intent(sangtianRuntimeFixture); assert.throws(() => validatePlayerActionIntent({ ...valid, intentType: "ASK", explicitOrder: true }, sangtianRuntimeFixture), /CONTRADICTION/); assert.throws(() => validatePlayerActionIntent({ ...valid, confidence: 0.2 }, sangtianRuntimeFixture), /PROPOSAL_REQUIRED/); assert.throws(() => validatePlayerActionIntent({ ...valid, proposedCapabilityId: undefined }, sangtianRuntimeFixture), /PROPOSAL_REQUIRED/); });

test("raw text is audit-only and settlement is deterministic and immutable", () => { const engine = new DeterministicSettlementEngine(); const contract = sangtianRuntimeFixture; const beforeContract = clone(contract); const beforeState = snapshot(contract); const first = engine.settle(contract, config(contract), beforeState, intent(contract, "alpha")); const second = engine.settle(contract, config(contract), beforeState, intent(contract, "beta")); assert.equal(first.kind, "ACCEPTED"); assert.equal(second.kind, "ACCEPTED"); if (first.kind !== "ACCEPTED" || second.kind !== "ACCEPTED") return; assert.deepEqual(first.result, second.result); assert.deepEqual(contract, beforeContract); assert.deepEqual(beforeState, snapshot(contract)); assert.equal(createHash("sha256").update(JSON.stringify(first.result)).digest("hex"), createHash("sha256").update(JSON.stringify(second.result)).digest("hex")); });
test("incomplete echo routing fails closed", () => { const broken = config(sangtianRuntimeFixture); broken.bindings[0].echoRoutes.pop(); assert.throws(() => validateSettlementPackage(broken, sangtianRuntimeFixture), /INCOMPLETE/); assert.equal(new DeterministicSettlementEngine().settle(sangtianRuntimeFixture, broken, snapshot(sangtianRuntimeFixture), intent(sangtianRuntimeFixture)).kind, "REJECTED"); });
test("stale revision and failed settlement do not mutate snapshot", () => { const state = snapshot(sangtianRuntimeFixture); const before = clone(state); const stale = { ...intent(sangtianRuntimeFixture), expectedStateRevision: 2 }; assert.equal(new DeterministicSettlementEngine().settle(sangtianRuntimeFixture, config(sangtianRuntimeFixture), state, stale).kind, "CONFLICT"); assert.deepEqual(state, before); });
test("semantic idempotency replays exactly and rejects key reuse", async () => { const contract = sangtianRuntimeFixture; const coordinator = new InMemorySettlementCoordinator(snapshot(contract)); const engine = new DeterministicSettlementEngine(); const first = await coordinator.submit(engine, contract, config(contract), "key", intent(contract)); const replay = await coordinator.submit(engine, contract, config(contract), "key", intent(contract)); assert.equal(first.kind, "ACCEPTED"); assert.equal(replay.kind, "REPLAYED"); if (first.kind === "ACCEPTED" && replay.kind === "REPLAYED") assert.deepEqual(first.result, replay.result); assert.equal((await coordinator.submit(engine, contract, config(contract), "key", { ...intent(contract), rawText: "different" })).kind, "REJECTED"); assert.equal(coordinator.read().state.revision, 1); });
test("concurrent submissions serialize one revision and return recoverable conflict", async () => { const contract = sangtianRuntimeFixture; const coordinator = new InMemorySettlementCoordinator(snapshot(contract)); const engine = new DeterministicSettlementEngine(); const a = intent(contract); const b = { ...a, actionId: `${contract.worldId}.action.two` }; const results = await Promise.all([coordinator.submit(engine, contract, config(contract), "a", a), coordinator.submit(engine, contract, config(contract), "b", b)]); assert.deepEqual(results.map((item) => item.kind).sort(), ["ACCEPTED", "CONFLICT"]); assert.equal(coordinator.read().state.revision, 1); });

test("delayed event remains scheduled then applies at most once and survives restart", () => { const contract = clone(sangtianRuntimeFixture); contract.capabilities[0].effectPatterns.push({ type: "WORLD.PRESSURE_CHANGED", constraints: {} }); contract.delayedRules[0].capabilityId = contract.capabilities[0].id; contract.delayedRules[0].condition = { all: [contract.causalRules[0].effects[0]] }; contract.delayedRules[0].visibility = { scope: "PUBLIC" }; const packageData = config(contract); packageData.bindings[0].delayedRuleIds = [contract.delayedRules[0].id]; const engine = new DeterministicSettlementEngine(); const outcome = engine.settle(contract, packageData, snapshot(contract), intent(contract)); assert.equal(outcome.kind, "ACCEPTED"); if (outcome.kind !== "ACCEPTED") return; const scheduled = outcome.result.events.find((event) => event.status === "SCHEDULED")!; assert.ok(scheduled); assert.ok(!outcome.result.snapshot.state.predicates.some((item) => JSON.stringify(item) === JSON.stringify(scheduled.predicate))); const notDue = engine.applyDue(contract, clone(outcome.result.snapshot)); assert.equal(notDue.pending[0].event.status, "SCHEDULED"); notDue.state.revision = scheduled.applyAtRevision!; const applied = engine.applyDue(contract, clone(notDue)); const replayed = engine.applyDue(contract, clone(applied)); assert.equal(applied.pending[0].event.status, "APPLIED"); assert.deepEqual(applied, replayed); });
test("cancelled delayed event is ignored and unrelated pending entries are preserved", () => { const contract = sangtianRuntimeFixture; const state = snapshot(contract); const event = { eventId: "sangtian.event.cancelled", runId: "sangtian.run.one", worldId: contract.worldId, worldTurnId: "sangtian.turn.one", sourceActionId: "sangtian.action.one", sourceRuleId: contract.delayedRules[0].id, originActorId: contract.roles[1].actorId, affectedActorIds: [contract.roles[1].actorId], predicate: contract.delayedRules[0].effects[0], status: "CANCELLED" as const, createdAtRevision: 0, visibility: contract.delayedRules[0].visibility, affectedPlayerSummaries: { [contract.roles[1].actorId]: "Cancelled." }, revealOriginActor: true, containsProtectedSecret: false, idempotencyKey: "sangtian.key.cancelled" }; state.events.push(event); state.pending.push({ event }); assert.deepEqual(new DeterministicSettlementEngine().applyDue(contract, state).pending, state.pending); });

test("protected block is immutable, sourced and locale-bound", () => { const contract = sangtianRuntimeFixture; const outcome = new DeterministicSettlementEngine().settle(contract, config(contract), snapshot(contract), intent(contract)); assert.equal(outcome.kind, "ACCEPTED"); if (outcome.kind !== "ACCEPTED") return; const block = outcome.result.protectedBlocks[0]; assert.equal(block.immutable, true); assert.doesNotThrow(() => validateProtectedNarrativeBlock(block, outcome.result.events, contract.styleProfile.locale)); assert.throws(() => validateProtectedNarrativeBlock({ ...block, sourcePredicateIds: ["ghost.event"] }, outcome.result.events, contract.styleProfile.locale), /GHOST/); assert.throws(() => validateProtectedNarrativeBlock({ ...block, locale: "fr" }, outcome.result.events, contract.styleProfile.locale), /LOCALE/); });
test("MODEL_ALLOWED creates no protected block", () => { const contract = sangtianRuntimeFixture; const outcome = new DeterministicSettlementEngine().settle(contract, config(contract, false), snapshot(contract), intent(contract)); assert.equal(outcome.kind, "ACCEPTED"); if (outcome.kind === "ACCEPTED") assert.deepEqual(outcome.result.protectedBlocks, []); });
test("all NarrativeDisposition variants are closed unions", () => { for (const value of [{ kind: "USE_ORIGINAL", draftId: "draft.one" }, { kind: "USE_REPAIRED", draftId: "draft.one", repairId: "repair.one" }, { kind: "USE_FALLBACK", fallbackId: "fallback.one", reason: "unavailable" }]) assert.deepEqual(validateNarrativeDisposition(value), value); for (const value of [{ kind: "USE_ORIGINAL" }, { kind: "OTHER", draftId: "draft.one" }, { kind: "USE_ORIGINAL", draftId: "draft.one", repairId: "repair.one" }]) assert.throws(() => validateNarrativeDisposition(value)); });
test("fallback is deterministic complete and contains no internal state fields", () => { const contract = sangtianRuntimeFixture; const engine = new DeterministicSettlementEngine(); const first = engine.settle(contract, config(contract), snapshot(contract), intent(contract)); const second = engine.settle(contract, config(contract), snapshot(contract), intent(contract)); assert.equal(first.kind, "ACCEPTED"); assert.equal(second.kind, "ACCEPTED"); if (first.kind !== "ACCEPTED" || second.kind !== "ACCEPTED") return; assert.equal(first.result.fallbackText, second.result.fallbackText); for (const marker of ["Outcome:", "Reaction:", "Pressure:", "Choose whether"]) assert.match(first.result.fallbackText, new RegExp(marker)); assert.doesNotMatch(first.result.fallbackText, /stateRevision|actorId|eventId|predicate/); assert.equal(first.result.disposition.kind, "USE_FALLBACK"); });
test("missing fallback assets and protected templates fail before play", () => { const contract = sangtianRuntimeFixture; const missing = config(contract); missing.fallback.nextDecisionPoint = ""; assert.throws(() => validateSettlementPackage(missing, contract), /FALLBACK_ASSET/); const noTemplate = config(contract); delete noTemplate.bindings[0].protectedTemplate; assert.throws(() => validateSettlementPackage(noTemplate, contract), /TEMPLATE_MISSING/); });
